### DISCUSSION TITLE
docker compose 不能识别设置mac地址，实际用控制台是可以按预期执行的。

### DISCUSSION THREAD

**Discussion by lvxj11** [1Panel-dev/1Panel#6973] [Q&A]
### 联系方式

lvxj11

### 1Panel 版本

社区版v1.10.12-lts

### 问题描述

容器使用macvlan网络，希望固定mac。在配置了mac选项点保存时报错：
服务内部错误: update failed when handle compose up, err: stderr: validating /opt/1panel/docker/compose/MediaDownloadAndManagement/docker-compose.yml: services.busybox.networks.default Additional property mac_address is not allowed , recreate failed: stderr: validating /opt/1panel/docker/compose/MediaDownloadAndManagement/docker-compose.yml: services.busybox.networks.default Additional property mac_address is not allowed
然后登陆终端，使用命令执行可以顺利执行并按预期固定了mac地址。

### 重现步骤

在yml文件使用macvlan网络，给容器网络配置mac_address: "xx:xx:xx:xx:xx:xx"选项点保存会报错。

### 期待的正确结果

可以正常保存并执行。

### 相关日志输出

```shell
服务内部错误: update failed when handle compose up, err: stderr: validating /opt/1panel/docker/compose/MediaDownloadAndManagement/docker-compose.yml: services.busybox.networks.default Additional property mac_address is not allowed , recreate failed: stderr: validating /opt/1panel/docker/compose/MediaDownloadAndManagement/docker-compose.yml: services.busybox.networks.default Additional property mac_address is not allowed
```

**Comment by wanghe-fit2cloud** [comment]
这个错误提示表明在使用 docker-compose.yml 文件时，mac_address 属性在当前网络配置中不被允许。可能原因是 docker-compose.yml 文件的格式或配置不符合 docker-compose 的版本规范，或当前的网络配置不支持该属性。

解决方法:

1.	检查 docker-compose 版本：确保 docker-compose.yml 文件中的 version 字段支持 mac_address 属性。例如，在 2.x 和 3.x 版本中可能有不同的属性支持情况。可以尝试以下调整：
	•	将 version 修改为 2.1 或 3.7（确保版本支持 mac_address）：
```
version: "3.7"
services:
  busybox:
    image: busybox
    networks:
      default:
        mac_address: "02:42:ac:11:00:02"
```
2.	移除 mac_address：如果并非必须指定 MAC 地址，删除 mac_address 属性以绕过该限制。
3.	检查网络配置：确保定义了 networks 部分，如果没有，增加如下配置：
```
networks:
  default:
    driver: bridge
```
4.	升级 docker-compose：确认 docker-compose 工具和 Docker 版本较新，以确保兼容 mac_address 的使用。

**Reply by lvxj11** [reply]
> 这个错误提示表明在使用 docker-compose.yml 文件时，mac_address 属性在当前网络配置中不被允许。可能原因是 docker-compose.yml 文件的格式或配置不符合 docker-compose 的版本规范，或当前的网络配置不支持该属性。
> 
> 解决方法:
> 
> 1. 检查 docker-compose 版本：确保 docker-compose.yml 文件中的版本字段支持 mac_address 属性。例如，在 2.x 和 3.x 版本中可能有不同的属性支持情况。尝试以下调整：
>    • 可以将版本修改为 2.1 或 3.7（确保版本支持 mac_address）：
> 
> ```
> version: "3.7"
> services:
>   busybox:
>     image: busybox
>     networks:
>       default:
>         mac_address: "02:42:ac:11:00:02"
> ```
> 
> 2. 删除 mac_address：如果不是必须指定 MAC 地址，则删除 mac_address 属性以绕过该限制。
> 3. 检查网络配置：确保定义了网络部分，如果没有，增加如下配置：
> 
> ```
> networks:
>   default:
>     driver: bridge
> ```
> 
> 4. 升级 docker-compose：确认 docker-compose 工具和 Docker 版本较新，以确保兼容 mac_address 的使用。

1. 已经尝试更改各种版本，还是会报错
2. 确实有需要
3. 已定义网络部分
4. 使用终端执行是可以的，所以docker和docker-compose工具都是支持此配置的。

**Reply by wanghe-fit2cloud** [reply]
麻烦提供一下 `第 4 点 的  docker-compose.yml` 文件。

**Reply by lvxj11** [reply]
```yaml
version: "3.9"
services:
  busybox:
    container_name: ip32-busybox
    image: busybox:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      default:
        mac_address: "02:42:C0:A8:38:20"
    environment:
      # - PUID=911         # uid
      # - PGID=911         # gid
      # - UMASK=0000
      - TZ=Asia/Shanghai
    volumes:
      - /root/appsData/busybox:/busybox
    command: sh -c "/busybox/start.sh"
networks:
  default:
    external: true
    name: myNetMACvlan
```
