### DISCUSSION TITLE
Use Github Actions to synchronize certificates to 1Panel

### DISCUSSION THREAD

**Discussion by dextercai** [1Panel-dev/1Panel#7677] [Show and tell]
Previously, I used Github Actions to regularly apply for certificates and sync them to the cloud platform (aliyun, tencent cloud etc.). Recently, I converged my all certificate application process from 1Panel to Actions.

The script was written based on the comment by [ColinZeb](https://github.com/ColinZeb) in [#discussioncomment-10932704](https://github.com/1Panel-dev/1Panel/discussions/6299#discussioncomment-10932704)

```
# if you enable mfa
- name: Generate auth code
  id: generate
  uses: nknguyengl/totp-generator@v1.0.0
  with:
    totp_key: ${{ secrets.MFA_KEY }}


- uses: dextercai/1panel_ssl_cert_uploader@v1-release
  with:
    username: "username"
    password: ${{ secrets.PASSWORD }}
    entrance_code: "example_code" # optional
    mfa_token: ${{ steps.generate.outputs.code }} # optional
    login_url: "https://example.com/api/v1/auth/login"
    mfa_login_url: "https://example.com/api/v1/auth/mfalogin"
    upload_url: "https://example.com/api/v1/websites/ssl/upload"
    ssl_id: 1
    description: "sync from actions"
    private_key_path: ./_.example.com.key
    certificate_path: ./_.example.com.pem

```
