### DISCUSSION TITLE
基于acme.sh的SSL证书申请失败替代方案

### DISCUSSION THREAD

**Discussion by chivehao** [1Panel-dev/1Panel#7733] [General]
> https://github.com/1Panel-dev/1Panel/issues/4828#issuecomment-2594536728
> 我家庭内网里的虚拟机，SSL证书经常性的申请失败。

提供个解决方案：

借助项目[acme.sh](https://github.com/acmesh-official/acme.sh)，建议使用[docker运行acme.sh](https://github.com/acmesh-official/acme.sh/wiki/Run-acme.sh-in-docker)

ssh进shell，给acme.sh分配目录：
```
mkdir -p /opt/1panel/apps/acme.sh
```

创建文件`docker-compose.yml`
```
vi docker-compose.yml
```

提供个我用的示例，使用的阿里云DNS和letsencrypt：
```
services:
  acme-sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    volumes:
      - ./out:/acme.sh
    network_mode: host
    command: daemon
    stdin_open: true
    tty: true
    restart: always
    environment:
      Ali_Key: xxx
      Ali_Secret: xxx
```

PS: 如果你内网拉取镜像有问题，请查看：<https://1panel.cn/docs/user_manual/containers/setting> 配置镜像加速，然后在1panel面板操作对应的按钮拉取

创建好后，运行容器：
```
docker compose up -d
```

容器跑起来后，接下来就是申请证书

ssh进服务器运行如下命令：

我使用的是letsencrypt，所以需要切换下，具体看acme.sh他们的官方文档
```
docker exec acme.sh --set-default-ca --server letsencrypt
```

申请证书
```
docker exec acme.sh --issue --dns dns_ali -d domain1.com -d domain1.com
```
PS: letsencrypt证书，是支持申请支持通配符的，比如`*.domain.com`这种

配置网站的SSL，进1panel面板操作：

`证书` => `上传证书` => `导入方式=选择服务器文件`

这里的路径，你需要进目录`/opt/1panel/apps/acme.sh/out`查看，

私钥文件后缀带Key是：`domain.com.key`

证书文件就是：`fullchain.cer`

创建好后，进网站的HTTPS配置，`Acme 账户`那选手动创建，然后选择你创建的证书即可。
