### ISSUE TITLE
[BUG]在「编排」页面使用「创建编排」创建的编排，被提示「来源」为本地

### ISSUE THREAD

**Issue by JueLuo99** [1Panel-dev/1Panel#1555]
### 联系方式

请在此联系

### 1Panel 版本

v1.3.6

### 问题描述

在「编排」页面使用「创建编排」创建的编排，被提示「来源」为本地，且 `该 compose 为 1Panel 编排外部创建。暂不支持启停操作。`

![image](https://github.com/1Panel-dev/1Panel/assets/25797524/5ba95065-b32c-44ff-af65-bdac884aa4f0)

![image](https://github.com/1Panel-dev/1Panel/assets/25797524/646bf02b-2184-48e7-8df1-c7f4291d5547)

已经参考 #491 ，确认 `docker-compose.yml` 中不包含 `name: ` 字段

### 重现步骤

1. 安装并登录 1Panel
2. 左侧导航栏「容器」→「编排」
3. 「创建编排」→「编辑」
4. 输入「文件夹」和 `docker-compose` 文件内容
5. 点击「确认」
6. 等待 1Panel 拉取并启动
7. 在「编排」页，「来源」显示为「本地」，且无法删除该编排
8. 点击该编排名称，提示 `该 compose 为 1Panel 编排外部创建。暂不支持启停操作。`（如上图所示）

### 期待的正确结果

- 通过面板「创建编排」创建的编排能够被正常删除
- 能够被正确支持 `docker-compose down` 等操作

### 附加信息

附所填写的 `docker-compose.yml` 文件内容
```yml
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /home/xxxxx/qbittorrent/config:/config
      - /home/xxxxx/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
```
