### ISSUE TITLE
[FEATURE] 应用商店的应用允许用户使用本地 Dockerfile 构建

### ISSUE THREAD

**Issue by wojiushixiaobai** [1Panel-dev/1Panel#1724]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

部分内网环境、私有仓库代码，或者测试时可以使用本地构建功能，不需要到服务器或者 容器 页面单独构建。
![a95361876bc01957cf0669a395b22bf2(1](https://github.com/1Panel-dev/1Panel/assets/24326988/72841502-eb41-4196-b7a5-babc5ce9db99)

### 请描述你建议的实现方案

Compose 本身支持 `--build` 参数
```yaml
version: '3.8'
services:
  test:
    image: test/test:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
     ...
```

```bash
docker compose up -d --build
```

如果不勾选构建功能，保持原样执行
```sh
docker compose up -d
```
