### ISSUE TITLE
[BUG] 使用编排模版创建编排无日志

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#1950]
### 1Panel 版本

1.5.0

### 问题描述

使用编排模版创建编排无执行日志

### 重现步骤

创建一个编排模版，创建编排时，来源选择编排模版，点击确认，无执行日志

**Comment by ssongliu** [comment]
感谢反馈！ 我们在本地复现一下该问题。

**Comment by ssongliu** [comment]
感谢反馈！我在开发环境未能复现该问题，方便提供一下编排模版吗。
<img width="669" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/1c293f00-a0cf-49d6-9627-eddbeb74de6b">

**Comment by CyJaySong** [comment]
```
version: "3"
services:
    rocketmq:
        container_name: RocketMQ-AtandAlone
        environment:
            NAMESRV_XMX: 512M
            NAMESRV_XMS: 256M
            NAMESRV_XMN: 256M
            BROKER_XMX: 512M
            BROKER_XMS: 256M
            BROKER_XMN: 256M
            NAMESRV_ADDR: localhost:9876
        restart: always
        image: xuchengen/rocketmq:5.1.3
        ports:
            - 8080:8080
            - 9876:9876
            - 10909:10909
            - 10911:10911
            - 10912:10912
        volumes:
            - rocketmq_data:/home/app/data
volumes: 
    rocketmq_data:

```
