### ISSUE TITLE
[BUG] Mysql数据库备份报错

### ISSUE THREAD

**Issue by DengQingNian** [1Panel-dev/1Panel#2363]
### 1Panel 版本

v1.6.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/117324885/82345514-2a16-455f-b192-1af9651ac358)
1、外部数据库
2、MySQL8.0.x

备份按钮或计划任务那边的备份功能会报错

### 重现步骤

备份按钮

### 相关日志输出

```shell
[2023-09-20 17:19:29] [INFO] start to backup database 【数据库名】to LOCAL  
[2023-09-20 17:19:29] [INFO] dump start at 2023-09-20 17:19:29
  
[2023-09-20 17:19:30] [ERROR] get create table sql failed, err: sql: expected 4 destination arguments in Scan, not 2  
[2023-09-20 17:19:30] [INFO] dump end at 2023-09-20 17:19:30, cost 1.29747649s
```

**Comment by DengQingNian** [comment]
备份目录有备份的文件了

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下 MySQL 具体版本和安装方式。
> 我们先在本地环境复现一下上述问题。

**Comment by DengQingNian** [comment]
> 麻烦提供一下 MySQL 具体版本和安装方式。
> 
> > 我们先在本地环境复现一下上述问题。


docker 部署的

``` yaml
version: '3.7'
services:
  # mysql
  mysql8-docker:
    image: mysql:8.0.33
    container_name: mysql8-docker
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    security_opt:
        - seccomp:unconfined
    healthcheck:
      test: /usr/bin/mysql --user=账号 --password=密码 --execute "SHOW DATABASES;"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=密码
    ports:
      - '46603:3306'
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    networks:
      - app_net
```
