### ISSUE TITLE
[BUG]自定义OpenResty的docker-compose.yml中的站点根目录后，无法创建站点

### ISSUE THREAD

**Issue by Godamanga** [1Panel-dev/1Panel#2375]
### 1Panel 版本

1.6.1

### 问题描述

```
services:
    openresty:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: openresty/openresty:1.21.4.2-0-focal
        labels:
            createdBy: Apps
        network_mode: host
        restart: always
        volumes:
            - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./conf/fastcgi_params:/usr/local/openresty/nginx/conf/fastcgi_params
            - ./conf/fastcgi-php.conf:/usr/local/openresty/nginx/conf/fastcgi-php.conf
            - ./log:/var/log/nginx
            - ./conf/conf.d:/usr/local/openresty/nginx/conf/conf.d/
            **- /docker/www:/www**
            - ./root:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime
version: "3"
```

### 重现步骤

编排文档中修改映射目录./www:www为/docker/www:www后就会出现一系列问题，显然创建web站时没有因为更改映射而调整，还是读取原来目录，自定义web根目录应该是很有必要的，现有的服务器向1Panel迁移中，一定会遇到不能更改根目录的问题，尤其涉及大批量静态文件不能全部迁移到openresty的site目录中。把站点放到openresty的安装目录下面，这不符合实际应用场景，也非常不安全，如果不能适配，1Panel基本没法使用
