### ISSUE TITLE
[FEATURE]多容器编排应用，自动生成的性能限制存在缺陷

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#2667]
### 1Panel 版本

v1.7.3

### 请描述您的需求或者改进建议

目前关于自动生成的`CPU`、内存等限制配置，当是多个容器应用时，只会对其中一个进行生成。

```
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
```

比如南墙WAF自动生成的配置如下

```
networks:
    1panel-network:
        external: true
services:
    uuwaf:
        command:
            - /run.sh
        container_name: ${CONTAINER_NAME}
        depends_on:
            - wafdb
        environment:
            - TZ=Asia/Shanghai
        image: uusec/nanqiang:v2.6.1
        links:
            - wafdb
        networks:
            - 1panel-network
        ports:
            - ${PANEL_APP_PORT_HTTP1}:80
            - ${PANEL_APP_PORT_HTTPS2}:443
            - ${PANEL_APP_PORT_HTTPS}:4443
        ulimits:
            nofile:
                hard: 102400
                soft: 102400
            nproc: 65535
        volumes:
            - wafshared:/uuwaf
    wafdb:
        container_name: ${CONTAINER_NAME}-db
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - TZ=Asia/Shanghai
            - INIT_ROCKSDB
            - MYSQL_ROOT_PASSWORD=Safe3.WAF
        image: percona:8
        networks:
            - 1panel-network
        volumes:
            - wafshared:/docker-entrypoint-initdb.d
            - wafdata:/var/lib/mysql
volumes:
    wafdata: null
    wafshared: null

```
