### ISSUE TITLE
[FEATURE] 希望可以增加设置网站root目录的功能

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2783]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

有些程序会有 **一套程序** 部署多个网站的需求
比如 项目结构:
/frontend/web 前台网站
/common/ 共用文件
/backend/web 后台网站

当前1p的主目录无法修改,因为还涉及到
waf | 防火墙规则
ssl | 网站证书
log | 网站日志
index | 网站 root 目录（PHP 运行环境 静态网站代码存放目录）
等,
希望可以配置 网站 root 目录
这样就可以将不同网站指向同一套源码目录

目前可以通过 **配置文件->openresty** 修改root的参数达到目的,不过发现一个问题,如果 **停止** 这个网站,再**开启**的时候, nginx root就会被系统覆盖为默认的了

测试过修改 **网站设置** 下的其他参数不会影响 root 参数

### 请描述你建议的实现方案

希望可以配置 网站 root 目录
这样就可以将不同网站指向同一套源码目录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先调研一下上述需求的可行性方案。

**Comment by 2234839** [comment]
![图片](https://github.com/1Panel-dev/1Panel/assets/28727933/6af9675f-095c-4d63-8bb3-0e28db2dc37e)

我通过编辑 compose 文件来实现指定域名到某个文件目录，供大家参考

```yaml
services:
    openresty:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: 1panel/openresty:1.21.4.3-3-1-focal
        labels:
            createdBy: Apps
        network_mode: host
        restart: always
        volumes:
            - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./conf/fastcgi_params:/usr/local/openresty/nginx/conf/fastcgi_params
            - ./conf/fastcgi-php.conf:/usr/local/openresty/nginx/conf/fastcgi-php.conf
            - ./log:/var/log/nginx
            - ./conf/conf.d:/usr/local/openresty/nginx/conf/conf.d/
            - ./www:/www
            - ./root:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime
            - ./1pwaf/data:/usr/local/openresty/1pwaf/data
            - /本机目录:/www/sites/站点域名/index

```
