### ISSUE TITLE
[BUG]應用商店安裝yourls時生成env參數可能有誤

### ISSUE THREAD

**Issue by bee10301** [1Panel-dev/1Panel#3206]
### 联系方式

github@bee.moe

### 1Panel 版本

1.8.5

### 问题描述

從應用商店安裝YOURLS時，產生的env如下:
```
="mysql"
//部分省略
PANEL_DB_HOST="mysql"
//部分省略
undefined="mysql"
```
應該不影響原應用執行，但應該有BUG建議確認一下。

### 重现步骤

從應用商店安裝YOURLS，確認以下路徑的env檔案
```
/opt/1panel/apps/yourls/yourls
```

### 附加信息

額外建議能保留參數，我另開issue

**Comment by zhengkunwang223** [comment]
感谢反馈 我们复现一下

**Comment by okxlin** [comment]
`data.yml`里设置了一个参数，但是`docker-compose.yml`里没有这个变量，

所以生成的env文件里的多一个这个反正是不影响实际容器。

原配置从官方`halo`那边抄过来改的……咸鱼懒得改……

```
          params:
            - envKey: YOURLS_DB_PORT
              key: mysql
              type: param
              value: "3306"
            - envKey: YOURLS_DB_PORT
              key: postgresql
              type: param
              value: "5432"
```
