### ISSUE TITLE
[BUG]定义变量的data.yml里的选择框规则bug

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#3275]
### 1Panel 版本

v1.8.5

### 问题描述

当使用两个选择框时，会使选择结果发生窜动。

已在群里讨论过。

![seafile-child20231211](https://github.com/1Panel-dev/1Panel/assets/61420215/3e459642-45bc-4e8e-b8c4-ded452b2b8bd)

### 重现步骤

简单例子，以[seafile](https://github.com/okxlin/appstore)为例

```
additionalProperties:
  formFields:
    - child:
        default: ""
        envKey: PANEL_DB_HOST
        labelEn: Database Service
        labelZh: 数据库服务
        required: true
        type: service
      default: mysql
      labelEn: Database Service
      labelZh: 数据库服务
      params:
        - envKey: SEAFILE_DB_PORT
          key: mysql
          type: param
          value: "3306"
      required: true
      type: apps
      values:
        - label: MySQL
          value: mysql
    - child:
        default: ""
        envKey: MEMCACHED_HOST
        labelEn: Memcached Service
        labelZh: Memcached 服务
        required: true
        type: service
      default: memcached
      labelEn: Memcached Service
      labelZh: Memcached 服务
      #params:
      #  - envKey: SEAFILE_DB_PORT
      #    key: mysql
      #    type: param
      #    value: "3306"
      required: true
      type: apps
      values:
        - label: Memcached
          value: memcached
        - label: LocalMemcached
          value: localmemcached
```
