### ISSUE TITLE
[BUG]测试本地应用报错

### ISSUE THREAD

**Issue by kohirei** [1Panel-dev/1Panel#4052]
### 1Panel 版本

v1.10.0-lts

### 问题描述

在编写本地应用点击安装后出现错误,后续打开应用商店一直服务异常
![image](https://github.com/1Panel-dev/1Panel/assets/88517920/96bc4f71-b582-419e-9b97-d51842a84a0b)
![image](https://github.com/1Panel-dev/1Panel/assets/88517920/3a9715b3-7329-4c9f-a680-3c154aeff61e)
已安装这里报错后读取不了，应用显示安装上了,docker编排也没有该应用
![image](https://github.com/1Panel-dev/1Panel/assets/88517920/3876a9e6-399a-4345-8a8c-639cf8fa4109)

### 重现步骤

搭建本地应用测试的文件
[Coze-Bot.zip](https://github.com/1Panel-dev/1Panel/files/14471878/Coze-Bot.zip)

### 相关日志输出

```shell
[31m2024/03/03 13:27:33 [Recovery] 2024/03/03 - 13:27:33 panic recovered:
POST /api/v1/apps/installed/search HTTP/1.1
Host: 192.168.124.11:9090
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh
Connection: keep-alive
Content-Length: 39
Content-Type: application/json
Cookie: _bl_uid=3glaws891tktRksC95wycetr5nXw; _pk_id.1.a05a=e38cc7a17dd7b8a5.1708350343.; Hm_lvt_7174bade1219f9cc272e7978f9523fc8=1708399500; pma_lang=zh_CN; pmaUser-1=JBTdJcvfRkTpZTuDKQ84mHjbjeXmDzrm3%2F%2BVi8Dfqe2UqRuMLB%2Bh%2FeDg2UA%3D; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IkRHVEtOa0tQVGtpdTl0eWtoVko4OXc9PSIsInZhbHVlIjoieVN5QmJGdmZ3NzBBRDc1aEpRRmZTL3NPM3daNGpPVy83Vm96bUkzcHdLcVJGa2hlN3BiZ1FzRU1qK1NGdEcvZE9WdmxsS0ZJMzBiZGlBK3pHMFkxTHlYQ0JadTFQOGFzSmFiY01xMjlWQVZ3ZmlNT0FnbVZraUlROE14aDU5L2hQU3Yyb0JnRnVYM29ZR1g3N2M5R2ZvcHc1LzZ2VitVZkkvQlk5MHM2Y3liajh2b3J1RTVDSDZLeW5WcDg0RDhLM1F4cUFldjE1Z01oczlMcHpmQ25GVFF5bGxHUlkrbjFXeElRNDBtdkcrND0iLCJtYWMiOiJlNDZlOWZjZmEwOTk2MjIyMzBhZDllMTE5Yzg4NzVlYTJjMjBkZTVmY2UyZTFlNjkzZmUzNWQwYzRiYmFkMTE1IiwidGFnIjoiIn0%3D; l=fBTTaSbrPlkIU3kYBO5B-urza7791IdXCkPzaNbMiIEGa1JFtFcwMNC9EalJSdtfgTfYrUtP04HeUdnHSj4g7NkDBeYQwo9ZNxv9-nYvHD1..; tfstk=eqPkngsNL8k5X0R_kuh5MpAIcp6xF3GIFkdKvXB4mmuHz2zEUK8qm20eTykrgtuE8DoEaW2XtPaQwaGdPbaSOXSOX1h3PzGB-6lyP1HGya8dXGCOM8pRDEjTeI65OMJN4wgfQWboBcYMuOySCIajbzoyyeF2EYp7SmAeTSAtFc-nmBRUi4SrmKJNAxdIuwF2dpMrlqmTvFJxBn6jKebcodGIUqgRXZbDdpMrlqmOoZv_dYujyGC..; token=34b8d24728fa2489714c1703d073e340; code-server-session=%24argon2id%24v%3D19%24m%3D65536%2Ct%3D3%2Cp%3D4%24toB5NQsz4mVRBOWszvl6Dg%24hOIP8ftGoIQ34iYHwT3T2nIuoFQiWyXQgZXQtCrgrD0; psession=40e37ef9-585b-4e68-be31-20fda79a1c65; arp_scroll_position=0
Origin: http://192.168.124.11:9090
Referer: http://192.168.124.11:9090/apps/all
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36


interface conversion: interface {} is nil, not string
runtime/iface.go:263 (0x40df64)
github.com/1Panel-dev/1Panel/backend/app/service/app_utils.go:697 (0x2b6a6e7)
github.com/1Panel-dev/1Panel/backend/app/service/app_utils.go:651 (0x2b6a148)
github.com/1Panel-dev/1Panel/backend/app/service/app_utils.go:622 (0x2b699b9)
github.com/1Panel-dev/1Panel/backend/app/service/app_install.go:707 (0x2b61804)
github.com/1Panel-dev/1Panel/backend/app/service/app_utils.go:1062 (0x2b6e5ee)
github.com/1Panel-dev/1Panel/backend/app/service/app_install.go:121 (0x2b5b188)
github.com/1Panel-dev/1Panel/backend/app/api/v1/app_install.go:33 (0x2f18894)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc5ed4a)
github.com/1Panel-dev/1Panel/backend/middleware/password_expired.go:24 (0x2f47069)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc5ed4a)
github.com/1Panel-dev/1Panel/backend/middleware/session.go:36 (0x2f46c1a)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc5ed4a)
github.com/1Panel-dev/1Panel/backend/middleware/jwt.go:15 (0x2f46928)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc5ed4a)
github.com/1Panel-dev/1Panel/backend/middleware/loading.go:22 (0x2f89ae4)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc5ed4a)
github.com/1Panel-dev/1Panel/backend/middleware/bind_domain.go:22 (0x2f898d0)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc5ed4a)
github.com/1Panel-dev/1Panel/backend/middleware/ip_limit.go:25 (0x2f894c4)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc5ed4a)
github.com/1Panel-dev/1Panel/backend/middleware/operation.go:25 (0x2f87690)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6bc59)
github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0xc6bc47)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6adfd)
github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0xc6adc0)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc69eba)
github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0xc69b4d)
github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0xc6967c)
net/http/server.go:2938 (0x87780d)
net/http/server.go:2009 (0x8736f3)
runtime/asm_amd64.s:1650 (0x472080)
[0m
```

**Comment by zhengkunwang223** [comment]
帖一下你本地应用的配置

**Comment by kohirei** [comment]
> 帖一下你本地应用的配置

发过压缩包了，里面就是配置
```
additionalProperties:
  formFields:
    - default: 7077
      edit: true
      envKey: PANEL_APP_PORT_HTTPS
      labelEn: Port
      labelZh: 端口
      required: true
      rule: paramPort
      type: number
    - default: 
      envKey: USER_AUTHORIZATION  
      labelEn: Authorization keys of the Discord users who initiate messages  
      labelZh: 授权密钥(多个请以,分隔)  
      required: true
      type: text
    - default: 
      envKey: BOT_TOKEN  
      labelEn: Bot-Token for listening to messages  
      labelZh: 监听消息的Bot-Token 
      required: true
      type: text
    - default: 
      envKey: GUILD_ID  
      labelEn: Server ID where all Bots are located  
      labelZh: 所有Bot所在的服务器ID
      required: true
      type: number
    - default: 
      envKey: COZE_BOT_ID  
      labelEn: Bot-ID managed by Coze  
      labelZh: 由coze托管的Bot-ID
      required: true
      type: text
    - default: 
      envKey: CHANNEL_ID  
      labelEn: Default channel  
      labelZh: 默认频道(目前版本下该参数仅用来活跃Bot)
      required: false
      type: text
    - default: 
      envKey: PROXY_SECRET  
      labelEn: PROXY_SECRET  
      labelZh: 接口密钥(多个请以,分隔)
      required: false
      type: text
    - default: Asia/Shanghai
      edit: true
      envKey: TIME_ZONE
      labelEn: Time zone
      labelZh: 时区
      required: true
      type: text
    - default: "true"
      edit: true
      envKey: Enable full context recording
      labelEn: ALL_DIALOG_RECORD_ENABLE
      labelZh: 是否启用全量上下文
      required: false
      type: select
      values:
          - label: "是"
            value: 1
          - label: "否"
            value: 0
    - default: 5
      edit: true
      envKey: Automatic channel deletion time
      labelEn: CHANNEL_AUTO_DEL_TIME
      labelZh: 频道自动删除时间(秒)
      required: false
      rule: paramPort
      type: number
```
