### ISSUE TITLE
[BUG] 容器网络模式与端口检查

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#4223]
### 联系方式

qyg2297248353@163.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

关于网络模式的检查
配置文件使用 network_mode
```yml
services:
  app:
    network_mode: host
```

对于 `无网络` `主机网络` `桥接网卡` `1panel-network` 网络的检查
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/ee3dff18-bb2a-4a9d-8a4d-45670db648aa)

+  `无网络` 与  `桥接网卡` 可以无需检查
+ `主机网络` 要使用脚本命令对系统进行端口检查
+ `1panel-network` 可保持默认网络检查与原有配置一致：
```yml
services:
  app:
    network_mode: 1panel-network
```
等价于
```yml
services:
  app:
    networks:
      - 1panel-network
```

当前已上线所有应用中只有 `openresty` 默认使用主机网络 host 模式，希望对端口检查能够个性化，增加网络模式的选择。

关于网络模式的选择我认为在家庭服务器中最为常用，由于路由器的存在，网络分配方式自然就会很多。有些冲突应用占用相同端口，并且无法修改的情况下，同时要与主机在同一网段下，单一的容器网络就无法满足安装需求。
例如：emby与jellyfin
都是占用 8096
并且只有在主机模式下 才能实现投屏以及网络唤醒
因此，一个主机不能用相同端口，又不能放在NTA网络下，桥接就是很好的解决办法，都分配了独立IP就不考虑端口占用的问题。
如果推出网络模式选择：
新问题就是，静态IP，要不要给桥接网络分配静态IP(静态IP解决最大的问题就是不用每次都去查看IP是否变化)

### 重现步骤

使用桥接方式安装相同应用，就会出现端口重复使用的检查提醒

### 期待的正确结果

- [ ] 新增容器网络模式选择
- [ ] 优化对不同网络模式的端口占用的检查
- [ ] 在 `无网络` 与  `桥接网卡` 以及 `主机网络` 模式下删除端口映射的选项
- [ ] 桥接模式下静态IP的支持

### 附加信息

[可以算Bug] 那是因为项目本身以容器为基础，那么对于容器的支持应该彻底一些。
[不算Bug] 现有发行的应用并没有网络模式的配置(虽然用户可以通过手动修改 `docker-compose.yml` 文件实现切换网络模式)
我认为是Bug,那是因为安装我所需要的服务确实遇到了此问题，希望能获得官方应用的支持。
