### ISSUE TITLE
[FEATURE] 添加zerotier支持

### ISSUE THREAD

**Issue by alterem** [1Panel-dev/1Panel#4275]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

添加zerotier支持

### 请描述你建议的实现方案

docker-compose.yml

```yaml
version: '3'
services:
  zerotier:
    container_name: zerotier
    image: zerotier/zerotier:latest
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - './data/zerotier-one:/var/lib/zerotier-one'
    devices:
      - /dev/net/tun
    command:
      - ${NETWORK_ID_1}
      - ${NETWORK_ID_2}
```
