### ISSUE TITLE
[FEATURE]商店增加dockurr/windows

### ISSUE THREAD

**Issue by meng-plus** [1Panel-dev/1Panel#4283]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

dockurr/windows 这个容器支持docker运行win系统 ，体验几天来说还是不错的，强烈建议添加

### 请描述你建议的实现方案
```yml
# https://hub.docker.com/r/dockurr/windows 
version: "3"
networks:
  1panel-network:
    external: true
services:
  windows11:
    image: dockurr/windows
    container_name: win_11
    devices:
      - /dev/kvm
      - /dev/vhost-net
    cap_add:
      - NET_ADMIN
    networks:
         - 1panel-network
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ./data/win:/storage
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "12"
      DISK_SIZE: "128G"
    device_cgroup_rules:
      - 'c *:* rwm'

```
