### ISSUE TITLE
期望支持自动化部署静态网站方案

### ISSUE THREAD

**Issue by ruibaby** [1Panel-dev/1Panel#430]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

目前 1Panel 创建静态网站只能够手动上传资源以供访问，所以期望能够通过某种自动化的方式来自动部署静态网站。目前纯前端的 SSG 或者 SPA 框架很多，相信这个特性能够很好的帮助这种框架部署网站。

### 请描述你建议的实现方案

我这里暂时有两个实现想法：

### 1. GitHub Action + 1Panel Deploy CLI

具体流程：

1. 在 1Panel 上创建静态网站会对应提供类似 website_id 和 website_secret 用于 CLI 鉴权。
2. CLI 大致使用方式：`1panel deploy --host=https://demo.1panel.cn --website_id=foo --website_secret=bar --i=./dist`
3. 配合 GitHub Action 或者其他 CI 工具（需要 1Panel 官方发布一个 Action 简化流程）：
    
    ```yaml
    name: Node.js CI
    
    on:
      push:
        branches: [ main ]
      # 或者 release 的时候部署
      release:
        types: 
          - created
    jobs:
      build:
        runs-on: ubuntu-latest
        needs: check
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@v2
    
        - name: Install pnpm
          uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.15.1
    
        - name: Use Node.js 16.x
          uses: actions/setup-node@v2
          with:
            node-version: 16.x
            cache: 'pnpm'
    
        - run: pnpm install
        - run: pnpm build
    
        - name: Deploy
          uses: 1Panel-Dev/static-deploy@main
          env:
            WEBSITE_ID: ${{ secrets.WEBSITE_ID }}
            WEBSITE_SECRET: ${{ secrets.WEBSITE_SECRET }}
            HOST: ${{ secrets.HOST }}
            TARGET: "dist/"
    ```

### 2. 类似于 Vercel / Netlify / Cloudflare Pages 的方案

大致流程：

1. 创建静态网站的时候支持通过 GitHub 或者其他托管平台选择仓库（可能需要引导去创建 GitHub App，并配置 Repository Access）。
2. 配置 **依赖安装命令**、**包管理器（yarn、pnpm、npm）**、**构建命令**、**构建产物目录**。
3. 完成配置之后即可自动在 1Panel 这边构建并部署。
4. 如果仓库有新的提交，1Panel 会这边自动部署。

从实现成本考虑，个人倾向于第一种。
