### ISSUE TITLE
[BUG]应用商店安装时，原始docker-compose.yml的`deploy`字段下内容会被1panel自动覆写

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#4340]
### 1Panel 版本

v1.10.2-lts

### 问题描述

例如
```
version: '3'
services:
  langchain-chatchat:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${GPU_DRIVER_TYPE}
              count: all
              capabilities: [gpu]
    image: registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.7
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

```

那么从应用商店安装时，会将以下覆写成CPU和内存相关设置

```
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${GPU_DRIVER_TYPE}
              count: all
              capabilities: [gpu]
```

- https://github.com/okxlin/appstore/tree/localApps/apps/langchain-chatchat

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/1d5d7e7e-de3d-44ea-8fc2-fbb119a0862a)

### 重现步骤

如上述
