### ISSUE TITLE
[BUG] OpenResty 又有问题了

### ISSUE THREAD

**Issue by lZiMUl** [1Panel-dev/1Panel#4813]
### 联系方式

lZiMUl@lzimul.top

### 1Panel 版本

v1.10.6-lts

### 问题描述

OpenResty 构建报错 启动报错

### 重现步骤

下载OpenResty后构建

### 期待的正确结果

正常运行

### 相关日志输出

```shell
OpenResty  | 2024/04/30 05:33:01 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:02 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:03 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:04 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:06 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:08 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:11 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:18 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:32 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | 2024/04/30 05:33:58 [emerg] 1#1: open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
OpenResty  | nginx: [emerg] open() "/usr/local/openresty/1pwaf/data/conf/waf.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:34
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/45619879/a7e2acb1-c66a-49d6-a0d3-fc252c3eed70)
![image](https://github.com/1Panel-dev/1Panel/assets/45619879/6eec645f-63ea-4dd4-bc75-e00b32d5fb93)

**Comment by lZiMUl** [comment]
修改了 docker-compose.yml 的 volumes 属性
可以运行了 但是代理没有效果
![image](https://github.com/1Panel-dev/1Panel/assets/45619879/40865b90-56fa-4600-8841-883dcabc99be)

**Comment by zhengkunwang223** [comment]
```yaml
services:
  openresty:
    image: 1panel/openresty:1.21.4.3-2-1-focal
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf/fastcgi_params:/usr/local/openresty/nginx/conf/fastcgi_params
      - ./conf/fastcgi-php.conf:/usr/local/openresty/nginx/conf/fastcgi-php.conf
      - ./log:/var/log/nginx
      - ./conf/conf.d:/usr/local/openresty/nginx/conf/conf.d/
      - ./www:/www
      - ./root:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime
      - ./1pwaf/data:/usr/local/openresty/1pwaf/data
    labels:
      createdBy: "Apps" 
```

使用这个，然后重建
