### ISSUE TITLE
[BUG]Fedora 40无法通过 主机 -> 防火墙 修改防火墙设置

### ISSUE THREAD

**Issue by ZnCookie** [1Panel-dev/1Panel#4842]
### 1Panel 版本

v1.10.6-lts

### 问题描述

Fedora 40下无法通过 主机 -> 防火墙 修改防火墙设置

### 重现步骤

设置前
```
[root@zncookie ~]# firewall-cmd --list-all
FedoraServer (default, active)
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: enp1s0
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 20000/tcp
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
尝试在 主机 -> 防火墙 里放行60022 TCP
重新用`firewall-cmd --list-all`查看防火墙配置 无变化
且测试相应端口无法连接

### 期待的正确结果

正确情况下，应该能控制防火墙来放行相应端口
