### ISSUE TITLE
[FEATURE] 应用商店添加 TDengine 时序数据库

### ISSUE THREAD

**Issue by Keene-Chen** [1Panel-dev/1Panel#5207]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

看到应用商店添加了 Grafana 和 Prometheus，所以希望添加 tdengine 涛思国产时序数据库 🙏🙏🙏
官网 docker 部署：[docker-tdengine](https://docs.taosdata.com/get-started/docker/)

1. `docker pull tdengine/tdengine:latest`
2. docker run
```
docker run -d -v ~/data/taos/dnode/data:/var/lib/taos \
  -v ~/data/taos/dnode/log:/var/log/taos \
  -p 6030:6030 -p 6041:6041 -p 6043-6060:6043-6060 -p 6043-6060:6043-6060/udp tdengine/tdengine
```
3. docker compose
```
services:
  tdengine:
    container_name: tdengine
    hostname: tdengine-server
    volumes:
      - ~/work/taos/log:/var/log/taos
      - ~/work/taos/data:/var/lib/taos
    ports:
      - 6030-6060:6030-6060
      - 6030-6060:6030-6060/udp
    image: tdengine/tdengine
networks:
  1panel-network:
    external: true
```
