### ISSUE TITLE
---

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#5427]
---

**Comment by wanghe-fit2cloud** [comment]
1、如果使用 env_file 来指定环境变量文件，要在应用启动前确保该文件的存在（不要使用 .env）
2、系统默认使用 .env 文件来管理环境变量，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/da48ebfa-cfcd-490f-9ac1-cbfb9a48bca1)

**Comment by QYG2297248353** [comment]
我在data.yml配置了选项，env，docker-compose.yml 中不在 environment 声明也可以吗？

假如 data.yml
```
    - default: "127.0.0.1"
      edit: true
      envKey: REDIS_HOSTNAME
      labelZh: Redis 主机
      labelEn: Redis Host
      required: true
      type: text
```
在docker-compose.yml 的 environment 中没有使用 ${REDIS_HOSTNAME} 容器也能读取到 REDIS_HOSTNAME 环境变量吗？

**Comment by wanghe-fit2cloud** [comment]
data.yml 文件中声明的参数，都会初始化到 .env 文件中。

**Comment by QYG2297248353** [comment]
问题是，容器不会读取 .env的所有变量，不使用
```
    env_file:
      - .env
```
指定一次，容器读取不到

**Comment by wanghe-fit2cloud** [comment]
> 问题是，容器不会读取 .env的所有变量，不使用
> 
> ```
>     env_file:
>       - .env
> ```
> 
> 指定一次，容器读取不到

替换成你自己维护的环境变量文件即可（不要使用 .env）。

**Comment by QYG2297248353** [comment]
上一个版本使用 env_file 指定就没有问题，应用也能正常安装，这么改造成很大困扰。

**Comment by wanghe-fit2cloud** [comment]
> 上一个版本使用 env_file 指定就没有问题，应用也能正常安装，这么改造成很大困扰。

近期版本没有修改过这里的逻辑。

**Comment by QYG2297248353** [comment]
> > 问题是，容器不会读取 .env的所有变量，不使用
> > ```
> >     env_file:
> >       - .env
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 指定一次，容器读取不到
> 
> 替换成你自己维护的环境变量文件即可。

没有每维护任何文件，就是依赖你们生成的.env文件，导入到容器中，用户只需要通过表单修改，容器正常能读取到

**Comment by QYG2297248353** [comment]
> > 上一个版本使用 env_file 指定就没有问题，应用也能正常安装，这么改造成很大困扰。
> 
> 近期版本没有修改过这里的逻辑。

其他机器的1Panel升级后安装指定了 .env 文件的应用都是这个问题，生成 .env 的逻辑变了

**Comment by wanghe-fit2cloud** [comment]
而且，`.env` 文件是 `docker-compose` 默认会读取的环境变量文件。
不需要你在 `docker-compose.yml` 文件中明确指定 `env_file` 来加载它。

**Comment by QYG2297248353** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/e2e94bd2-505c-4d3d-b636-bf7e7b8481ba)


> 而且，`.env` 文件是 `docker-compose` 默认会读取的环境变量文件。 不需要你在 `docker-compose.yml` 文件中明确指定 `env_file` 来加载它。

没有，他不会读取，容器启动失败，告诉我环境变量不存在

**Comment by wanghe-fit2cloud** [comment]
https://docs.docker.com/compose/environment-variables/set-environment-variables/

**Comment by wanghe-fit2cloud** [comment]
如果还有疑问，可以在微信交流群添加 `王贺` 好友，继续讨论你这个疑问。

**Comment by wanghe-fit2cloud** [comment]
给你提供一个本地执行的例子，可以参考：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/8780a9bf-bda7-4161-ae11-69b92efd2977)

**Comment by QYG2297248353** [comment]
好吧，既然你们认为这不是一个问题，我也不想继续纠缠这个问题。
你要是愿意可以测试一下配置文件

``yaml
version: "3.8"

networks:
  1panel-network:
    external: true

name: immich

services:
  immich-pg14-vectors:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_DB:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
    volumes:
      - ${IMMICH_ROOT_PATH}/pg14/data:/var/lib/postgresql/data

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.106.2
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ${IMMICH_ROOT_PATH}/data/cache:/cache
    env_file:
      - .env

  immich-server:
    depends_on:
      - immich-pg14-vectors
    image: ghcr.io/immich-app/immich-server:v1.106.2
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    command: [ "start.sh", "immich" ]
    devices:
      - ${IMMICH_DRIVE_PATH:-/dev/dri}:/dev/dri
    volumes:
      - ${IMMICH_ROOT_PATH}/data/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    env_file:
      - .env

```data.yaml
additionalProperties:
  formFields:
    - child:
        default: ""
        envKey: PANEL_REDIS_HOST
        required: true
        type: service
      default: redis
      envKey: PANEL_REDIS_TYPE
      labelZh: Redis 服务
      labelEn: Redis Service
      required: true
      type: apps
      values:
        - label: Redis
          value: redis
    - default: "/home/immich-app"
      edit: true
      envKey: IMMICH_ROOT_PATH
      labelZh: 数据持久化路径
      labelEn: Data persistence path
      required: true
      type: text
    - default: 2283
      edit: true
      envKey: PANEL_APP_PORT_HTTP
      labelZh: WebUI 端口
      labelEn: WebUI port
      required: true
      rule: paramPort
      type: number
    - default: "/dev/dri"
      edit: true
      envKey: IMMICH_DRIVE_PATH
      labelZh: 硬件驱动路径
      labelEn: Drive path
      required: true
      type: text
    - default: "Asia/Shanghai"
      edit: true
      envKey: TZ
      labelZh: 时区
      labelEn: Timezone
      required: true
      type: text
    - default: ""
      edit: true
      envKey: DB_PASSWORD
      labelEn: Database Password
      labelZh: 数据库连接密码
      random: true
      required: true
      rule: paramComplexity
      type: password
    - default: 5432
      edit: true
      envKey: PANEL_APP_PORT_DB
      labelZh: 数据库 端口
      labelEn: Database Port
      required: true
      rule: paramPort
      type: number
    - default: "immich-pg14-vectors"
      disabled: true
      envKey: DB_HOSTNAME
      labelZh: 数据库 主机地址
      labelEn: Database Host
      required: true
      type: text
    - default: "postgres"
      disabled: true
      envKey: DB_USERNAME
      labelZh: 数据库 用户名
      labelEn: Database User
      required: true
      type: text
    - default: "immich"
      disabled: true
      envKey: DB_DATABASE_NAME
      labelZh: 数据库 名称
      labelEn: Database Name
      required: true
      type: text
    - default: "127.0.0.1"
      edit: true
      envKey: REDIS_HOSTNAME
      labelZh: Redis 主机
      labelEn: Redis Host
      required: true
      type: text
    - default: 6379
      edit: true
      envKey: REDIS_PORT
      labelZh: Redis 端口
      labelEn: Redis Port
      required: true
      rule: paramPort
      type: number
    - default: 0
      edit: true
      envKey: REDIS_DBINDEX
      labelZh: Redis 索引
      labelEn: Redis Index
      required: true
      type: number
    - default: ""
      edit: true
      envKey: REDIS_USERNAME
      labelZh: Redis 用户名
      labelEn: Redis Username
      required: false
      type: text
    - default: ""
      edit: true
      envKey: REDIS_PASSWORD
      labelZh: Redis 密码
      labelEn: Redis Password
      required: false
      type: password
    - default: "XLM-Roberta-Large-Vit-B-16Plus"
      edit: true
      envKey: MACHINE_LEARNING_PRELOAD__CLIP
      labelEn: Machine Learning Preload Model
      labelZh: 机器学习 预加载模型
      required: false
      type: text
    - default: "buffalo_l"
      edit: true
      envKey: MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION
      labelEn: Machine Learning Preload Model
      labelZh: 人脸识别 预加载模型
      required: false
      type: select
      values:
        - label: antelopev2
          value: "antelopev2"
        - label: buffalo_l
          value: "buffalo_l"
        - label: buffalo_m
          value: "buffalo_m"
        - label: buffalo_s
          value: "buffalo_s"
    - default: "https://hf-mirror.com"
      edit: true
      envKey: HF_ENDPOINT
      labelZh: Hugging Face 服务地址
      labelEn: Hugging Face Endpoint
      required: false
      type: text
    - default: ""
      edit: true
      envKey: HTTP_PROXY
      labelZh: HTTP 代理
      labelEn: HTTP Proxy
      required: false
      type: text
    - default: ""
      edit: true
      envKey: HTTPS_PROXY
      labelZh: HTTPS 代理
      labelEn: HTTPS Proxy
      required: false
      type: text
    - default: "localhost,127.0.0.1,::1"
      edit: true
      envKey: NO_PROXY
      labelZh: 绕过代理地址
      labelEn: No Proxy
      required: false
      type: text

```

data.yml 中的 envKey 与 实际需求的 环境变量一致
如果你删掉 env_file 启动应用，将会无法正常启动

**Comment by wanghe-fit2cloud** [comment]
上面已经给你提到，是你使用问题。
如果还是有疑问，可以通过微信交流。

**Comment by QYG2297248353** [comment]
> https://docs.docker.com/compose/environment-variables/set-environment-variables/

使用 命令运行是可以正常读取 .env 文件，使用命令行，我本地也没有问题，我不知道你们安装应用的逻辑，执行安装确实无法读取

**Comment by thksdhr** [comment]
[最开始我也没正确理解env_file的意思，后来我仔细的查看了docker的官方文档后才正确理解了。](https://docs.docker.com/reference/compose-file/services/#env_file)

实际上`env_file`是取代`environment`这个块而存在的，它的作用是为了方便应对一些特定的情况时用于分割文件的。

`env_file`和`.env`作用不相同，`.env`更多的是去设置compose file的全局变量，可以定义要融合的compose.yaml文件这些。而`env_file`是解决单个`services服务`中的变量很多需要分离或者多个`services服务`复用相同的一些环境变量的情况。

对于这个错误实际就是对于`env_file`理解错误导致的，如果要用`插值Interpolation``${VAR}`的方法来指定变量，使用`env_file`是错误的，你应该在全局`.env`文件中配置对应的插值，并在启动时使用`docker compose up --env-file /path/.env`来指定全局env变量。如果你是想分割配置，那你应该在`env_file、environment`中二选一，或者两者同时使用时不要重复配置一个变量。

下面是一个例子:
compose.yaml
```
services:
  msdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-2022-latest
    hostname: mssql-2022-taozig
    user: root:root
    restart: always
    ports:
      - "1433:1433"
    env_file:
      - path: ./env_files/mssql.env
        required: true
    volumes:
      - ./volumes:/var/opt/mssql
```
mssql.env (env_file)
```
TZ="Asia/Shanghai"
ACCEPT_EULA="Y"
SA_PASSWORD="yourpasswd"
MSSQL_PID="Express"
```

最终使用`docker compose config`的输出内容如下:
```
(base) root@hyperv001:/data/docker/mssql-server# docker compose config
name: mssql-server
services:
  msdb:
    container_name: mssql-server-2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      SA_PASSWORD: yourpasswd
      TZ: Asia/Shanghai
    hostname: mssql-2022-taozig
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 1433
        published: "1433"
        protocol: tcp
    restart: always
    user: root:root
    volumes:
      - type: bind
        source: /data/docker/mssql-server/volumes
        target: /var/opt/mssql
        bind:
          create_host_path: true
networks:
  default:
    name: mssql-server_default
```

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
[At the beginning, I didn't understand the meaning of env_file correctly. I knew that I carefully checked the official docker documentation before I understood it correctly. ](https://docs.docker.com/reference/compose-file/services/#env_file)

In fact, `env_file` exists instead of the `environment` block, and its function is to facilitate the partitioning of files in response to some specific situations.

`env_file` and `.env` have different functions. `.env` is more about setting global variables of compose file, which can define the compose.yaml files to be fused. `env_file` solves the situation where many variables in a single service service need to be separated or multiple service services reuse some of the same environment variables.

This error is actually caused by the `env_file` understanding error. If you want to use the `interpolation Interpolation``${VAR}` method to specify the variable, using `env_file` is wrong. You should configure the corresponding interpolation in the global `.env` file and use `docker compose up --env-file /path/.env` to specify the global env variable at startup. If you want to split the configuration, you should choose one of the two in `env_file, environment`, or use both at the same time, do not repeatedly configure a variable.

Here is an example:
compose.yaml
```
services:
  msdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-2022-latest
    hostname: mssql-2022-taozig
    user: root:root
    restart: always
    Ports:
      - "1433:1433"
    env_file:
      - path: ./env_files/mssql.env
        required: true
    Volumes:
      - ./volumes:/var/opt/mssql
```
mssql.env (env_file)
```
TZ="Asia/Shanghai"
ACCEPT_EULA="Y"
SA_PASSWORD="yourpasswd"
MSSQL_PID="Express"
```

The output content of the final use of `docker compose config` is as follows:
```
(base) root@hyperv001:/data/docker/mssql-server# docker compose config
name: mssql-server
services:
  msdb:
    container_name: mssql-server-2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      SA_PASSWORD: yourpasswd
      TZ: Asia/Shanghai
    hostname: mssql-2022-taozig
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      default: null
    Ports:
      - mode: ingress
        target: 1433
        published: "1433"
        protocol: tcp
    restart: always
    user: root:root
    Volumes:
      - type: bind
        source: /data/docker/mssql-server/volumes
        target: /var/opt/mssql
        bind:
          create_host_path: true
networks:
  default:
    name: mssql-server_default
```
