### ISSUE TITLE
[FEATURE]应用商店添加Wallos

### ISSUE THREAD

**Issue by alvinthisss** [1Panel-dev/1Panel#5925]
### 1Panel 版本

1.10.13

### 请描述您的需求或者改进建议

应用商店添加Wallos，

### 附加信息
Wallos 是一款功能强大、开源且可自行托管的 Web 应用程序，旨在帮助您轻松管理财务。告别复杂的电子表格和昂贵的财务软件 - Wallos 简化了跟踪费用的过程，并帮助您更好地控制财务生活。
[wallos github地址](https://github.com/ellite/Wallos)
```
#wallos docker compose文件
version: '3.0'

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Asia/Shanghai'
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
```
_No response_
