### ISSUE TITLE
[BUG]系统快照需要忽略 stdout: stderr: tar: xxx socket ignored

### ISSUE THREAD

**Issue by hhhguany** [1Panel-dev/1Panel#6240]
### 1Panel 版本

 v1.10.13-lts

### 问题描述

我自己创建了一个容器 gitlab，并将数据目录放在  `/opt/1panel/docker/gitlab` 中，在执行“系统快照”计划任务的时候，一直不成功。报错信息如下：
```shell
Write 1Panel basic information: Done 
Backup 1Panel system files: Done 
Backup Docker configuration file: Done 
Backup installed apps from 1Panel: Done 
Backup 1Panel data directory: do handle tar failed, stdout: stderr: tar: ./docker/gitlab/data/gitlab-rails/sockets/gitlab.socket: socket ignored
tar: ./docker/gitlab/data/redis/redis.socket: socket ignored
tar: ./docker/gitlab/data/gitaly/run/gitaly-287/sock.d/intern: socket ignored
tar: ./docker/gitlab/data/gitaly/gitaly.socket: socket ignored
tar: ./docker/gitlab/data/postgresql/.s.PGSQL.5432: socket ignored
tar: ./docker/gitlab/data/gitlab-workhorse/sockets/socket: socket ignored
, err: exit status 1 
Backup local backup directory for 1Panel: Done 
Create snapshot file: Waiting 
Snapshot size:  
Upload snapshot file: Waiting 
```

根据我的了解，执行 tar 打包文件的时候，会忽略 socket 文件，然后会有此报错信息。建议忽略 `stdout: stderr: tar: xxx socket ignored` 这个错误信息，具体方式可以参考[这篇文章](https://www.builddesigncreate.com/index.cgi?mode=question_details&questionid=2014092018081731024)。

### 重现步骤

1. 根据下面的 compsose 文件 创建 gitlab 容器：
```
services:
  grocy:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
        - PATH = /opt/gitlab/embedded/bin:/opt/gitlab/bin:/assets:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - LANG = C.UTF-8
        - EDITOR = /bin/vi
        - GITLAB_ALLOW_SHA1_RSA = false
        - TERM = xterm
    volumes:
        - /opt/1panel/docker/gitlab/config:/etc/gitlab
        - /opt/1panel/docker/gitlab/data:/var/opt/gitlab
        - /opt/1panel/docker/gitlab/logs:/var/log/gitlab
    ports:
        - 22:22
        - 443:443
        - 80:80
    restart: unless-stopped
```

2. 然后在计划任务中，添加一个系统快照。执行这个任务，会失败并报错。

### 相关日志输出
见描述。
