### ISSUE TITLE
[FEATURE] 希望商店增加应用： nginxWebUI

### ISSUE THREAD

**Issue by jian263994241** [1Panel-dev/1Panel#6476]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

希望商店增加应用： nginxWebUI 

### 请描述你建议的实现方案

https://github.com/cym1102/nginxWebUI

### 附加信息

```
services:
  nginxWebUi-server:
    image: cym1102/nginxwebui:latest
    volumes:
      - type: bind
        source: "/home/nginxWebUI"
        target: "/home/nginxWebUI"
    environment:
      BOOT_OPTIONS: "--server.port=8080"
    privileged: true
    network_mode: "host"
```
