### ISSUE TITLE
[FEATURE] 希望商店增加应用：Clouddrive2

### ISSUE THREAD

**Issue by jian263994241** [1Panel-dev/1Panel#6477]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

希望商店增加应用：Clouddrive2

### 请描述你建议的实现方案

https://www.clouddrive2.com/docker.html

### 附加信息

```
services:
  cloudnas:
    image: cloudnas/clouddrive2
    container_name: clouddrive2
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    volumes:
      - <path to accept cloud mounts>:/CloudNAS:shared
      - <path to app data>:/Config
      - <other local shared path>:/media:shared #optional media path of host
    devices:
      - /dev/fuse:/dev/fuse
    restart: unless-stopped
    pid: "host"
    privileged: true
    network_mode: "host"
```
