### ISSUE TITLE
[FEATURE] 应用商店添加 apaache nifi etl工具

### ISSUE THREAD

**Issue by whoamixl** [1Panel-dev/1Panel#6735]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

应用商店新增apache nifi的应用支持

### 请描述你建议的实现方案
```yaml
services:
  nifi:
    cap_add:
      - NET_ADMIN # low port bindings
    image: apache/nifi:1.16.0
    container_name: nifi-dev
    ports:
      - 18443:18443 # HTTPS interface
    environment:
      NIFI_WEB_HTTPS_PORT: "18443"
      NIFI_WEB_PROXY_HOST: "192.168.2.99:18443"
      SINGLE_USER_CREDENTIALS_USERNAME: xxx
      SINGLE_USER_CREDENTIALS_PASSWORD: xxxxxxxxxxxx  # must over 12
    volumes:
      - ./timezone:/etc/timezone
      - ./self-lib:/opt/nifi/nifi-current/extensions
      - ./out:/opt/nifi/out
      - ./xml2json.xsl:/opt/nifi/template/xml2json.xsl
    restart: always
```

只有配置https才有认证，认证密码必须大于12位

### 附加信息

我提供的docker-compose只是我的需求是这样的，具体配置还得调研
