### ISSUE TITLE
[FEATURE] 添加 r-nacos

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#6921]
### 1Panel 版本

1.19.0

### 请描述您的需求或者改进建议

https://github.com/nacos-group/r-nacos

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。

**Comment by wanghe-fit2cloud** [comment]
应用商店现已提供 Nacos，如果满足需求可以直接使用。

**Comment by wanghe-fit2cloud** [comment]
也可以参考官方提供的部署方案：

#### 方式1: 通过docker 运行


```
#stable是最新正式版本号，也可以指定镜像版本号，如： qingpan/rnacos:v0.4.0
docker pull qingpan/rnacos:stable  
docker run --name mynacos -p 8848:8848 -p 9848:9848 -p 10848:10848 -d qingpan/rnacos:stable
```

docker 的容器运行目录是 /io，会从这个目录读写配置文件

##### docker 版本说明

应用每次打包都会同时打对应版本的docker包 ，qingpan/rnacos:$tag 。

每个版本会打两类docker包

|docker包类型|tag 格式| 示例 |说明 |
|--|--|--|--|
|gnu debian包|$version| qingpan/rnacos:v0.4.0 | docker包基于debian-slim,体积比较大(压缩包36M,解压后102M),运行性能相对较高;|
|musl alpine包|$version-alpine| qingpan/rnacos:v0.4.0-alpine | docker包基于alpine,体积比较小(压缩包11M,解压后34M),运行性能相对较低;|


如果不观注版本，可以使用最新正式版本tag: 

+ 最新的gnu正式版本: `qingpan/rnacos:stable`
+ 最新的alpine正式版本: `qingpan/rnacos:stable-alpine`


#### 方式2: 通过docker-compose 运行

单机部署样列:

[docker-compose.yaml](https://github.com/nacos-group/r-nacos/blob/master/docker/docker-compose/r-nacos-simple/docker-compose.yaml)

```yaml
# 集群部署样例,数据目录: ./data
version: '3.8'

services:
  nacos:
    image: qingpan/rnacos:stable
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - ./data:/io:rw
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=admin
      - RNACOS_HTTP_PORT=8848
    restart: always

```

集群部署样列: [docker-compose.yaml](https://github.com/nacos-group/r-nacos/blob/master/docker/docker-compose/r-nacos-cluster/docker-compose.yaml)
