### ISSUE TITLE
[BUG]1panel面板中官方应用商店中的[7.4.1] Redis，一键安装存在问题

### ISSUE THREAD

**Issue by huanglian666** [1Panel-dev/1Panel#6970]
### 1Panel 版本

v1.10.20-lts

### 问题描述

一键安装Redis警告
```shell
WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
```

### 重现步骤

通过面板官方的应用商店，默认方式，一键安装Redis

### 期待的正确结果

#期待
希望官方可以把这个配置加入到官方应用商店的默认配置选项中，期待官方采纳！！！！

### 相关日志输出

```shell
WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
```

### 附加信息

#解决方案
官方应用商店中的docker-compose文件中新增配置选项
```yaml
services:
  redis:
    sysctls:
      - net.core.somaxconn=512
```
