### ISSUE TITLE
[FEATURE] 请求应用商店创建通用自定义模板，方便用户自助将自建容器转为应用商店已安装应用，便于通过计划任务自动备份容器配置 

### ISSUE THREAD

**Issue by NJYZ-96** [1Panel-dev/1Panel#6980]
### 1Panel 版本

 v1.10.20-lts

### 请描述您的需求或者改进建议

通过应用商店安装的应用可以方便的进行网页跳转，安装目录跳转，最重要的是可以通过计划任务来自动化备份数据；
而自建容器相比之下就会麻烦很多。

但无限多的容器应用，靠1Panel官方或者少量第三方应用商店的开发者独自慢慢适配是不现实的，效率也太低了。

请求应用商店创建通用自定义模板，方便用户自助将自建容器转为应用商店已安装应用，便于通过计划任务自动备份容器配置 

### 请描述你建议的实现方案

那么能不能让使用者也能自己把自建容器转为应用商店已安装应用呢，我测试了一个方法，是可行的：
>这里用一个取巧的办法实现自建容器转为应用商店已安装应用，简单来说就是借用应用商店的模板，手动修改 compose 文档为自建容器的。

请求应用商店创建通用自定义模板，方便用户自助将自建容器转为应用商店已安装应用，便于通过计划任务自动备份容器配置 

* 把简单的使用说明放在应用介绍页
* 默认的环境变量只保留版本、端口号、数据文档夹路径
![截图_20241107002534](https://github.com/user-attachments/assets/153f0580-211d-42c4-bec6-5527e13e32ad)
* 可以写两个版本的模板，一个`latest`：最新镜像，网络配置为  1panel-network；一个`latest-host`：最新镜像，网络配置为host

```
services:
  【此处改为小写字母的应用名称】:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:【此处改为容器内部端口】"
    volumes:
      - "${DATA_PATH}:【此处改为容器内部路径，供持久化保存配置】"
    image: 【此处改为容器镜像名称】:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
```

* 再找一个通用性强一些的应用图标，类似于
![647643f9d68b4c9f8f3f674e9c0340c0](https://github.com/user-attachments/assets/1cff5771-a1ef-4a5e-9c9a-f09045c49fa1)

* 其他的类似于端口外部访问、CPU内存限制和正常一样就行。
