### ISSUE TITLE
[BUG] waf开启后，导致笔记软件TriliumNote同步失败

### ISSUE THREAD

**Issue by dwdcth** [1Panel-dev/1Panel#7116]
### 联系方式

1310049536@qq.com

### 1Panel 版本

专业版： v1.10.21-beta.1

### 问题描述

waf开启后，导致笔记软件TriliumNote同步失败
软件地址 https://github.com/TriliumNext/Notes
在拦截记录里面看到了这个软件的有些请求被拦截，关闭waf 后仍然没法同步

### 重现步骤

1、关闭waf的前提下，按照trilium服务端

```yaml
services:
  trilium:
	image: triliumnext/notes:v0.90.11-beta
	container_name: trilium
    restart: unless-stopped
	ports:
	  - "127.0.0.1:8010:8080"
	volumes:
	  - ./data/trilium-data:/home/node/trilium-data
```
2、到 https://github.com/TriliumNext/Notes 下载 客户端v0.90.11-beta，设置服务端的ip端口和密码，可以正常同步
3、开启waf 后，无法正常同步，而且关闭waf也没法同步
报错如下：
```
'Request to GET https://ip:port/api/sync/changed?instanceId=E4Yo0Hle2Isw&lastEntityChangeId=0&logMarkerId=Y48tGux0Hh failed, error: 401  Logged in session not found', stack: Error: Request to GET https://ip:port/api/sync/changed?instanceId=E4Yo0Hle2Isw&lastEntityChangeId=0&logMarkerId=Y48tGux0Hh failed, error: 401  Logged in session not found
```
