### ISSUE TITLE
[Bug] Folder naming capitalization issue when manually creating an arrangement

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#7380]
### Contact Information

Anye

### 1Panel Version

Pro： v1.10.21-lts

### Problem Description

When manually creating an orchestration, the folder name contains uppercase letters, which will create two orchestration results (one of which is wrong). The final generated folder name is uppercase (normal), and the container starts normally.
![45d6961933cf9223f230dcfe04d11a97](https://github.com/user-attachments/assets/f938756d-8276-4496-bc05-4754bd41342a)
![42e7bf37f72ff550f3f0d0f3a06144f9](https://github.com/user-attachments/assets/5ce66c39-4a3b-4c13-b46e-9c0225d88e2e)
![7b8948cbe5c5762ba04d01f987811d21](https://github.com/user-attachments/assets/c58593bc-9833-49e0-8b6e-849bbc3d5157)

### Steps to Reproduce

Manually create an orchestration, fill in `AutoBangumi` for the folder name, and fill in
```yaml
networks:
1panel-network:
external: true
services:
AutoBangumi:
image: "ghcr.io/estrellaxd/auto_bangumi:latest"
container_name: AutoBangumi
volumes:
- ./config:/app/config
- ./data:/app/data
ports:
- "7892:7892"
networks:
- 1panel-network
restart: unless-stopped
environment:
- TZ=Asia/Shanghai
```
You can reproduce it
