### ISSUE TITLE
[Bug] Using container template, arrangement error, unable to read environment variables

### ISSUE THREAD

**Issue by zguiyang** [1Panel-dev/1Panel#7604]
### 1Panel Version

社区版 v1.10.22-lts 更新

### Problem Description

在我手动创建一个affine的docker-compose.yml 模板后，在编排中选中并填入所需变量，点击确定后，出现错误。
我已经将env_file 修改为1panel.env,并且我在1panel创建的该容器目录下手动执行docker-compose up -d可以运行。

<img width="1952" alt="image" src="https://github.com/user-attachments/assets/9ca3592e-e655-4511-b1b1-c60b9038fb86" />
<img width="950" alt="image" src="https://github.com/user-attachments/assets/18364fbf-cc57-425e-87fd-aeb4680692ae" />

### Steps to Reproduce

使用以下配置作为模板
容器编排选取模板
输入对应的变量，点击确定就会出现

环境变量
```
AFFINE_REVISION=stable
PORT=3010
UPLOAD_LOCATION=
CONFIG_LOCATION=
DB_USERNAME=affine
DB_PASSWORD=
DB_DATABASE=
DB_DATA_LOCATION=

```
componse.yml

```
name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_server
    ports:
      - '${PORT:-3010}:3010'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    env_file:
      - 1panel.env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - 1panel.env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    container_name: redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${DB_USERNAME}", '-d', "${DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

```
