### ISSUE TITLE
[Feature] appstore add gitlab

### ISSUE THREAD

**Issue by wang-qa** [1Panel-dev/1Panel#8034]
### 1Panel Version

v1.10.26-lts

### Please describe your needs or suggestions for improvements

极狐 https://gitlab.cn/docs/jh/install/docker.html
gitlab https://docs.gitlab.com/install/docker/installation/

极狐runner https://gitlab.cn/docs/runner/install/docker.html
gitlabrunner https://docs.gitlab.com/runner/install/docker/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在后续版本考虑上架上述两款应用。
如果你已经有 docker 容器化部署经验，建议提供 docker-compose.yml 文件，以便我们更好地进行适配和上架工作。

**Comment by wang-qa** [comment]
image ：

- registry.gitlab.cn/omnibus/gitlab-jh:latest
- gitlab/gitlab-ce:latest


> 相关安装文档指南
> 极狐 https://gitlab.cn/docs/jh/install/docker.html
> gitlab https://docs.gitlab.com/install/docker/installation/
> 
> 极狐runner https://gitlab.cn/docs/runner/install/docker.html
> gitlabrunner https://docs.gitlab.com/runner/install/docker/

使用 Docker Compose 安装极狐GitLab 
```ymal
version: '3.6'
services:
  web:
    image: 'registry.gitlab.cn/omnibus/gitlab-jh:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
```


使用 Docker swarm 模式安装极狐GitLab
```ymal
version: "3.6"
services:
  gitlab:
    image: registry.gitlab.cn/omnibus/gitlab-jh:latest
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt
```

**Comment by wanghe-fit2cloud** [comment]
```
registry.gitlab.cn/omnibus/gitlab-jh:latest
gitlab/gitlab-ce:latest
```

请问，这两个镜像是一样的吗？

**Comment by wang-qa** [comment]
> ```
> registry.gitlab.cn/omnibus/gitlab-jh:latest
> gitlab/gitlab-ce:latest
> ```
> 
> 请问，这两个镜像是一样的吗？

一样
registry.gitlab.cn/omnibus/gitlab-jh:latest 为国内极狐镜像（极狐GitLab 是 GitLab 中国发行版（JH））
gitlab/gitlab-ce:latest 为 gitlab社区版

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> ```
> registry.gitlab.cn/omnibus/gitlab-jh:latest
> gitlab/gitlab-ce:latest
> ```
>
> Are these two mirrors the same?

Same
registry.gitlab.cn/omnibus/gitlab-jh:latest is a domestic extreme fox mirror (the extreme fox GitLab is the GitLab China distribution (JH))
gitlab/gitlab-ce:latest is the gitlab community version

**Comment by sineld** [comment]
+1

**Comment by wanghe-fit2cloud** [comment]
@wang-qa 
麻烦发一下你本地正常运行的 docker-compose.yml，刚在本地环境测试，应用容器可以正常启动，但是浏览器访问始终不正常，怀疑可能和 external_url 的配置有关，不是特别确定。

**Comment by wang-qa** [comment]
1. 使用 宿主IP:容器port 访问 
2. 修改 docker中的gitlab配置 [https://developer.aliyun.com/article/922952](https://developer.aliyun.com/article/922952)
3. 进入仓库时，会跳转异常(ip问题)，手动修改为宿主IP:容器port即可(替换域名)

时间久了 忘了咋改了 
```yaml
services:
  gitlab:
    image: gitlab/gitlab-ee
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'
    ports:
      - '32080:80'
      - '3443:443'
      - '2022:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
```
