### ISSUE TITLE
[Feature] Roundcube supports PostgreSQL in the app store

### ISSUE THREAD

**Issue by JinkaiNiu** [1Panel-dev/1Panel#8042]
### 1Panel Version

专业版 v1.10.26-lts

### Please describe your needs or suggestions for improvements

根据Roundcube官方说明，目前已经支持PostgreSQL数据库，烦请应用市场上的Roundcube 配置 增加支持下 PostgreSQL数据库 谢谢！

![Image](https://github.com/user-attachments/assets/d235978b-e016-4acb-ae12-460a6b3b75e2)

### Please describe the solution you suggest

建议应用商店Roundcube 应用，增加支持PostgreSQL数据库~

![Image](https://github.com/user-attachments/assets/b337d064-31cd-4c4d-881a-0ba31767769c)

**Comment by wanghe-fit2cloud** [comment]
可以的，建议提供一下 compose 文件，方便我们后续适配和上架。

**Comment by JinkaiNiu** [comment]
> 可以的，建议提供一下 compose 文件，方便我们后续适配和上架。

我这暂时还没看到官方有明确的文档 给出compose 配置 能否看下官方帮忙适配下呢？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Yes, it is recommended to provide a compose file for our subsequent adaptation and release.

I haven't seen the official documentation yet. I've given the compose configuration. Can I read the official help to adapt?

**Comment by 1265578519** [comment]
我觉得很适合我新手docker，1panel真正让我实现了零知识零负担管理服务器，我唯一需要做的就是买一份专业版，和给服务器续费，仅此而已，几台闲置的Linux服务器都整上了比特彗星，倒是希望官方也能上架下应用商店

![Image](https://github.com/user-attachments/assets/72f6405a-8f52-4820-8193-a0ef6de98cc5)

![Image](https://github.com/user-attachments/assets/9a4d4be5-8703-433f-864e-4752b365b8a0)

仓库
https://hub.docker.com/r/wxhere/bitcomet-webui
建议v2.12.3及以上，或者使用latest的最新版
```
services:
    sandbox:
        container_name: bitcomet-webui
        image: wxhere/bitcomet-webui:latest
        volumes:
            # mounts the host directory into the container to store config files
            - ./BitComet:/root/.config/BitComet:rw
            # mounts a host directory into the container to store downloaded files
            - ./Downloads:/root/Downloads:rw
        ports:
            # BitComet WebUI port
            - 6080:6080
            # BitTorrent ports
            - 6082:6082
            - 6082:6082/udp
        environment:
            - BITCOMET_WEBUI_PORT=6080
            - BITCOMET_BT_PORT=6082
            - WEBUI_USERNAME=admin
            - WEBUI_PASSWORD=itzmx.com

```

配置文件可选，但是能内置上就更好了，BitComet.xml 推荐设置
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<BitComet>
  <Settings>
    <DiskCacheMaxSizeMB>256</DiskCacheMaxSizeMB>
    <LTSeedCacheMaxSizeMB>256</LTSeedCacheMaxSizeMB>
    <StartupAutoRunTask>true</StartupAutoRunTask>
    <PassportLastUser></PassportLastUser>
    <PassportLastUserPassword></PassportLastUserPassword>
    <GlobalMaxUploadRate>10485760</GlobalMaxUploadRate>
    <ConditionAutoStopTask>false</ConditionAutoStopTask>
    <bittorrent.max_connections_per_ltseed>10</bittorrent.max_connections_per_ltseed>
    <network.max_connections>1500</network.max_connections>
    <ListenPort>6082</ListenPort>
    <network.start_connect_interval_ms>0</network.start_connect_interval_ms>
    <network.max_connecting_connections>60</network.max_connecting_connections>
    <network.max_connecting_connections_per_tracker>10000</network.max_connecting_connections_per_tracker>
    <network.tcp_connection_timeout>10</network.tcp_connection_timeout>
    <LastSaveLocation>/root/Downloads</LastSaveLocation>
    <bittorrent.enable_v1_upgrade_to_v2>true</bittorrent.enable_v1_upgrade_to_v2>
    <bittorrent.torrent_http_try_max_count>1000</bittorrent.torrent_http_try_max_count>
    <bittorrent.torrent_http_try_interval>5</bittorrent.torrent_http_try_interval>
    <system.compact_memory_interval>0</system.compact_memory_interval>
    <dht.udp_send_queue_threshold>1</dht.udp_send_queue_threshold>
    <network.dns_query_thread_count>100</network.dns_query_thread_count>
    <network.enable_open_dns>false</network.enable_open_dns>
    <EnableDHT>false</EnableDHT>
    <bittorrent.anti_leech_stable_sec>180</bittorrent.anti_leech_stable_sec>
    <bittorrent.anti_leech_min_byte>10000</bittorrent.anti_leech_min_byte>
    <bittorrent.anti_leech_banned_ports>15000</bittorrent.anti_leech_banned_ports>
    <bittorrent.anti_leech_banned_peer_ids>XL0018</bittorrent.anti_leech_banned_peer_ids>
    <RssFetchInterval>2</RssFetchInterval>
    <RssFeedMaxItems>5</RssFeedMaxItems>
    <EnableAutoDownloadRssTorrent>true</EnableAutoDownloadRssTorrent>
    <bittorrent.utp_after_holepunch>0</bittorrent.utp_after_holepunch>
    <bittorrent.save_connected_peers_only>true</bittorrent.save_connected_peers_only>
    <bittorrent.separate_sources_for_failed_piece>false</bittorrent.separate_sources_for_failed_piece>
    <bittorrent.max_torrent_size_mb>100</bittorrent.max_torrent_size_mb>
    <HttpDownloadTryAgainMaxCount>10000</HttpDownloadTryAgainMaxCount>
    <HttpDownloadDefaultConnectionNumber>300</HttpDownloadDefaultConnectionNumber>
    <http.max_mirror_count>1000</http.max_mirror_count>
    <HttpDownloadConnectionCacheSize>16777216</HttpDownloadConnectionCacheSize>
    <TotalUpload>0</TotalUpload>
    <TotalDownload>0</TotalDownload>
    <WebInterfaceUsername>admin</WebInterfaceUsername>
    <WebInterfacePassword>itzmx.com</WebInterfacePassword>
    <WebInterfacePort>6080</WebInterfacePort>
    <EnableAddTrackerList>true</EnableAddTrackerList>
    <TrackerListForNewTorrent>http://tracker1.itzmx.com:8080/announce&#13;
http://tracker2.itzmx.com:6961/announce&#13;
http://tracker3.itzmx.com:6961/announce&#13;
http://tracker4.itzmx.com:2710/announce&#13;
udp://tracker1.itzmx.com:8080/announce&#13;
udp://tracker2.itzmx.com:6961/announce&#13;
udp://tracker3.itzmx.com:6961/announce&#13;
udp://tracker4.itzmx.com:2710/announce&#13;
http://tracker.opentrackr.org:1337/announce&#13;
udp://tracker.opentrackr.org:1337/announce</TrackerListForNewTorrent>
    <TrackerListUpdateUrl>http://github.itzmx.com/1265578519/OpenTracker/master/tracker.txt</TrackerListUpdateUrl>
    <TrackerListUpdateUrlList>http://github.itzmx.com/1265578519/OpenTracker/master/tracker.txt</TrackerListUpdateUrlList>
    <EnableBtTaskIpFilter>true</EnableBtTaskIpFilter>
  </Settings>
</BitComet>

```
这个v2.12.3版本可以调整network.max_connecting_connections为750，后续修复了在改回60

Linux centos 7安装1panel面板搭建容器docker用法，在vps服务器中使用编排功能搭建比特彗星bitcomet-webui版本
https://bbs.itzmx.com/thread-111086-1-1.html

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I think it is very suitable for me for a newbie docker. 1panel really allows me to implement zero-knowledge and zero-burden management server. The only thing I need to do is to buy a professional version and renew the server. That's all, several idle Linux servers have been put on Bit Comet. I hope the official can also put the app store on the shelves.

![Image](https://github.com/user-attachments/assets/72f6405a-8f52-4820-8193-a0ef6de98cc5)

storehouse
https://hub.docker.com/r/wxhere/bitcomet-webui
It is recommended to use the latest version of latest v2.12.3 or above.
```
services:
    sandbox:
        container_name: bitcomet-webui
        image: wxhere/bitcomet-webui:latest
        Volumes:
            # mounts the host directory into the container to store config files
            - ./BitComet:/root/.config/BitComet:rw
            # mounts a host directory into the container to store downloaded files
            - ./Downloads:/root/Downloads:rw
        Ports:
            # BitComet WebUI port
            - 6080:6080
            # BitTorrent ports
            - 6082:6082
            - 6082:6082/udp
        environment:
            - BITCOMET_WEBUI_PORT=6080
            - BITCOMET_BT_PORT=6082
            - WEBUI_USERNAME=admin
            - WEBUI_PASSWORD=itzmx.com

```

The configuration file is optional, but it is better to be built-in. BitComet.xml recommended settings
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<BitComet>
  <Settings>
    <DiskCacheMaxSizeMB>256</DiskCacheMaxSizeMB>
    <LTSeedCacheMaxSizeMB>256</LTSeedCacheMaxSizeMB>
    <StartupAutoRunTask>true</StartupAutoRunTask>
    <PassportLastUser></PassportLastUser>
    <PassportLastUserPassword></PassportLastUserPassword>
    <GlobalMaxUploadRate>10485760</GlobalMaxUploadRate>
    <ConditionAutoStopTask>false</ConditionAutoStopTask>
    <bittorrent.max_connections_per_ltseed>10</bittorrent.max_connections_per_ltseed>
    <network.max_connections>1500</network.max_connections>
    <ListenPort>6082</ListenPort>
    <network.start_connect_interval_ms>0</network.start_connect_interval_ms>
    <network.max_connecting_connections>60</network.max_connecting_connections>
    <network.max_connecting_connections_per_tracker>10000</network.max_connecting_connections_per_tracker>
    <network.tcp_connection_timeout>10</network.tcp_connection_timeout>
    <LastSaveLocation>/root/Downloads</LastSaveLocation>
    <bittorrent.enable_v1_upgrade_to_v2>true</bittorrent.enable_v1_upgrade_to_v2>
    <bittorrent.torrent_http_try_max_count>1000</bittorrent.torrent_http_try_max_count>
    <bittorrent.torrent_http_try_interval>5</bittorrent.torrent_http_try_interval>
    <system.compact_memory_interval>0</system.compact_memory_interval>
    <dht.udp_send_queue_threshold>1</dht.udp_send_queue_threshold>
    <network.dns_query_thread_count>100</network.dns_query_thread_count>
    <network.enable_open_dns>false</network.enable_open_dns>
    <EnableDHT>false</EnableDHT>
    <bittorrent.anti_leech_stable_sec>180</bittorrent.anti_leech_stable_sec>
    <bittorrent.anti_leech_min_byte>10000</bittorrent.anti_leech_min_byte>
    <bittorrent.anti_leech_banned_ports>15000</bittorrent.anti_leech_banned_ports>
    <bittorrent.anti_leech_banned_peer_ids>XL0018</bittorrent.anti_leech_banned_peer_ids>
    <RssFetchInterval>2</RssFetchInterval>
    <RssFeedMaxItems>5</RssFeedMaxItems>
    <EnableAutoDownloadRssTorrent>true</EnableAutoDownloadRssTorrent>
    <bittorrent.utp_after_holepunch>0</bittorrent.utp_after_holepunch>
    <bittorrent.save_connected_peers_only>true</bittorrent.save_connected_peers_only>
    <bittorrent.separate_sources_for_failed_piece>false</bittorrent.separate_sources_for_failed_piece>
    <bittorrent.max_torrent_size_mb>100</bittorrent.max_torrent_size_mb>
    <HttpDownloadTryAgainMaxCount>10000</HttpDownloadTryAgainMaxCount>
    <HttpDownloadDefaultConnectionNumber>300</HttpDownloadDefaultConnectionNumber>
    <http.max_mirror_count>1000</http.max_mirror_count>
    <HttpDownloadConnectionCacheSize>16777216</HttpDownloadConnectionCacheSize>
    <TotalUpload>0</TotalUpload>
    <TotalDownload>0</TotalDownload>
    <WebInterfaceUsername>admin</WebInterfaceUsername>
    <WebInterfacePassword>itzmx.com</WebInterfacePassword>
    <WebInterfacePort>6080</WebInterfacePort>
    <EnableAddTrackerList>true</EnableAddTrackerList>
    <TrackerListForNewTorrent>http://tracker1.itzmx.com:8080/announce
http://tracker2.itzmx.com:6961/announce
http://tracker3.itzmx.com:6961/announce
http://tracker4.itzmx.com:2710/announce
udp://tracker1.itzmx.com:8080/announce
udp://tracker2.itzmx.com:6961/announce
udp://tracker3.itzmx.com:6961/announce
udp://tracker4.itzmx.com:2710/announce
http://tracker.opentrackr.org:1337/announce
udp://tracker.opentrackr.org:1337/announce</TrackerListForNewTorrent>
    <TrackerListUpdateUrl>http://github.itzmx.com/1265578519/OpenTracker/master/tracker.txt</TrackerListUpdateUrl>
    <TrackerListUpdateUrlList>http://github.itzmx.com/1265578519/OpenTracker/master/tracker.txt</TrackerListUpdateUrlList>
    <EnableBtTaskIpFilter>true</EnableBtTaskIpFilter>
  </Settings>
</BitComet>

```
This v2.12.3 version can adjust network.max_connecting_connections to 750, and subsequently fixed it and was changed back to 60

Linux centos 7 installation of 1panel panel to build container docker usage, use orchestration function to build bitcomet-webui version in vps server
https://bbs.itzmx.com/thread-111086-1-1.html
