### ISSUE TITLE
[Bug] Write environment variables in Docker .env file does not take effect

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#8383]
### 1Panel Version

v1.10.25-lts

### Problem Description

我在应用商店一键部署了 bitwarden，在该项目目录下的 `.env` 文件中写入官方文档中提到的环境变量来指定 `DOMAIN`，保存，然后重启该项目，发现新加环境变量并未被读取，访问该反代域名下的子路径会显示 404.

### Steps to Reproduce

然后我在面板侧栏的容器里找到该项目，点击更多，点击编辑，在最底部的环境变量框里（此处的内容和 .env 中的不一样）填入上述环境变量，重启，访问正常。

请问是 1panel 的设计逻辑如此，忽略 .env 中的环境变量还是 bug？

### Related log output

```shell

```

**Comment by wanghe-fit2cloud** [comment]
你有在 docker-compose.yaml 文件中引用上述提到的环境变量吗？

**Comment by W4J1e** [comment]
> 你有在 docker-compose.yaml 文件中引用上述提到的环境变量吗？

没有。实测在应用商店升级应用不勾选“自定义 docker-compose.yml  ”会覆盖 docker-compose.yml 的内容，同样 `.env` 文件中手动添加的变量也丢失了。

所以如果我希望升级并能保存手动添加的环境变量，最好的办法是不是直接写在 docker-compose.yml 里而非 .env 里，然后勾选“自定义docker-compose.yml ”呢？

更新：

实测在 docker-compose.yml 硬写环境变量再重启应用，环境变量没有生效。内容如下：

```yml
    bitwarden:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - DOMAIN=https://a.com/abc
            - SIGNUPS_ALLOWED=false
            - INVITATIONS_ALLOWED=false    
```
            
那么是否可以给 `.env` 设置持久化或者移动到持久化目录下，在 docker-compose.yml 中指定 `.env` 的路径避免升级时手动添加的环境变量丢失呢？
