### ISSUE TITLE
[Feature] Appstore adds PostgreSQL support for cassdoor

### ISSUE THREAD

**Issue by xiwangly2** [1Panel-dev/1Panel#8532]
### 1Panel Version

v1.10.29-lts

### Please describe your needs or suggestions for improvements

我需要让应用商店的 Casdoor 支持 PostgreSQL 数据库，目前 [apps/casdoor](https://github.com/1Panel-dev/appstore/tree/dev/apps/casdoor) 仅支持 MySQL

我尝试过自己 fork 那个仓库修改，可是 Casdoor 对于不同数据库的配置格式不太一样

例如需要这样的更改：

docker-compose.yml
```yaml
-       driverName: mysql
+       driverName: ${PANEL_DB_DRIVER_NAME}
```
data.yml
```yaml
      envKey: PANEL_DB_TYPE
      labelEn: DBType
      labelZh: 数据库类型
      required: true
      type: select
      values:
        - label: MySQL
          value: mysql
        - label: MariaDB
          value: mariadb
+       - label: PostgreSQL
+         value: postgres
```

```conf
# 切换成 MySQL 时：
PANEL_DB_DRIVER_NAME=mysql
PANEL_DB_DATA_SOURCE=${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@tcp(${PANEL_DB_HOST}:${PANEL_DB_PORT})/

# 切换成 PostgreSQL 时：
PANEL_DB_DRIVER_NAME=postgres
PANEL_DB_DATA_SOURCE="user=${PANEL_DB_USER} password=${PANEL_DB_USER_PASSWORD} host=${PANEL_DB_HOST} port=${PANEL_DB_PORT} sslmode=disable dbname=${PANEL_DB_NAME}"
```

但是目前我并不了解 1panel 的 appstore yaml 如何自定义像这样嵌套了变量的复杂一点的配置值

如果可以的话，麻烦新增 PostgreSQL 数据库的选项支持，谢谢
