### ISSUE TITLE
[Feature] Added Ollama support for AMD GPU

### ISSUE THREAD

**Issue by Wuqiyang312** [1Panel-dev/1Panel#8541]
### 1Panel Version

v1.10.29-lts

### Please describe your needs or suggestions for improvements

Want to enable ollama-supported AMD GPUs in APP Marketplace

### Please describe the solution you suggest

docker run -d --device /dev/kfd --device /dev/dri -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:rocm

### Additional Information

URL: https://hub.docker.com/r/ollama/ollama

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，这个需求可能需要在应用商店上架 ollama-rocm 应用来实现。

**Comment by wanghe-fit2cloud** [comment]
麻烦在你的服务器上手动执行一下 `docker-compose up -d` 命令，测试该应用是否能正常启动，docker-compose.yml 内容如下：

```yaml
services:
  ollama:
    image: ollama/ollama:0.6.8-rocm
    container_name: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    networks:
      - 1panel-network
    volumes:
      - ./data:/root/.ollama
    tty: true
    devices:
      - /dev/kfd
      - /dev/dri
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
```
