### ISSUE TITLE
[Feature] Hope Wanli Database joins the app store

### ISSUE THREAD

**Issue by xiahao90** [1Panel-dev/1Panel#8697]
### 1Panel Version

 社区版 v1.10.29-lts

### Please describe your needs or suggestions for improvements

把这个万里数据库加入应用商店哦，是个mysql国产版，有些需要国产要求的可以用。https://hub.docker.com/r/greatsql/greatsql

### Please describe the solution you suggest

把这个万里数据库加入应用商店哦，是个mysql国产版，有些需要国产要求的可以用。https://hub.docker.com/r/greatsql/greatsql

**Comment by wanghe-fit2cloud** [comment]
该应用支持单机和集群两种模式，但集群模式涉及更多容器和复杂配置，不太适合通过应用商店维护。若后续上架，将考虑提供单机模式版本。

**Comment by libs-cloud** [comment]
单机模式 就足够完成各项工作。这个数据库版本确实目前很火，也有博主实验后做出的数据对比确实比传统的mysql性能表现更加优异。这也加大了你们的时间维护成本。这东西一旦火了肯定会一直更新

**Comment by wanghe-fit2cloud** [comment]
> 单机模式 就足够完成各项工作。这个数据库版本确实目前很火，也有博主实验后做出的数据对比确实比传统的mysql性能表现更加优异。这也加大了你们的时间维护成本。这东西一旦火了肯定会一直更新

好的，后续版本考虑上架该应用。

**Comment by xiahao90** [comment]
@wanghe-fit2cloud 求大佬尽快上架哦，信创要求越来月多了

**Comment by GreatSQL** [comment]
感谢支持，我是GreatSQL的社区负责人，GreatSQL是MySQL的开源分支，是MySQL/Percona/MariaDB很好的平替选择，github主站 http://github.com/GreatSQL ，官网 https://greatsql.cn ，欢迎来了解哈

**Comment by xiahao90** [comment]
@GreatSQL 负责人请去 https://github.com/1Panel-dev/appstore 提交一个

**Comment by GreatSQL** [comment]
> [@GreatSQL](https://github.com/GreatSQL) 负责人请去 https://github.com/1Panel-dev/appstore 提交一个

我还没用过1Panel，怎么提交呢，请给个参考流程/教程，谢谢

**Comment by xiahao90** [comment]
> > [@GreatSQL](https://github.com/GreatSQL) 负责人请去 https://github.com/1Panel-dev/appstore 提交一个
> 
> 我还没用过1Panel，怎么提交呢，请给个参考流程/教程，谢谢

https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8

**Comment by xiahao90** [comment]
> > [@GreatSQL](https://github.com/GreatSQL) 负责人请去 https://github.com/1Panel-dev/appstore 提交一个
> 
> 我还没用过1Panel，怎么提交呢，请给个参考流程/教程，谢谢

猜测应该是把mysql的复制过来改改描述logo就行了。 @GreatSQL

**Comment by wanghe-fit2cloud** [comment]
@GreatSQL 
可以提供一下容器的 docker run 命令或 docker-compose.yml 文件（本地测试通过即可），后续的应用打包和上架我来处理。

**Comment by GreatSQL** [comment]
> [@GreatSQL](https://github.com/GreatSQL) 可以提供一下容器的 docker run 命令或 docker-compose.yml 文件（本地测试通过即可），后续的应用打包和上架我来处理。

我们已有提供Docker镜像，包括在hub.docker.com以及国内阿里云、腾讯云都有资源，详情参考我们的仓库：https://gitee.com/GreatSQL/GreatSQL-Docker/tree/master/GreatSQL

下面是简述
1、启动一个最基本的实例
```
docker run -d --name greatsql --hostname=greatsql greatsql/greatsql

# 阿里云ACR资源
docker run -d --name greatsql --hostname=greatsql registry.cn-beijing.aliyuncs.com/greatsql/greatsql

# 腾讯云TCR资源
docker run -d --name greatsql --hostname=greatsql ccr.ccs.tencentyun.com/greatsql/greatsql
```

2、利用docker-compose.yml启动实例

docker-compose.yml参考
```
# /data/docker/greatsql.yml
version: '2'

services:
  greatsql:
    image: greatsql/greatsql
    container_name: greatsql
    hostname: greatsql
    network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
```

启动
```
docker-compose -f /data/docker/greatsql.yml up -d
```

3、启动一个三节点的MGR
这是一个 docker-compose.yml 参考样例：https://gitee.com/GreatSQL/GreatSQL-Docker/blob/master/GreatSQL/docker-compose/mgr-3nodes.yml ，修改模板中的几个必要参数（主要是IP地址）后，保存文件 /data/docker/greatsql-mgr.yml ，即可启动

```
docker-compse -f /data/docker/greatsql-mgr.yml up -d
```

4、更多启动参数
详情参考： https://gitee.com/GreatSQL/GreatSQL-Docker/tree/master/GreatSQL#docker-compose环境变量参数介绍

以上，谢谢 @wanghe-fit2cloud @xiahao90

**Comment by wanghe-fit2cloud** [comment]
有个疑问：在实际使用中，是否都是默认允许 root 密码为空？
如果不是，是否支持通过环境变量设置 root 密码？

**Comment by wanghe-fit2cloud** [comment]
强制用户设置密码（root_password），yaml 文件如下：
```yaml
services:
  greatsql:
    image: greatsql/greatsql:8.0.32-27
    container_name: greatsql
    hostname: greatsql
    restart: unless-stopped
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Shanghai
```
