### ISSUE TITLE
[Bug] 1.10.29 lts, ​​timed task is indefinitely executed... The docker side is stuck, and the task side is stuck...

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#8721]
### 1Panel Version

1.10.29 lts

### Problem Description

![Image](https://github.com/user-attachments/assets/979dd030-ffd5-4c57-a560-dd0799ad1b04) 这都7:47了 还执行中..
底层docker compose 那边卡了2个容器，导致这边任务状态就卡住了...

等于说，一个任务进程无限挂起了？

因为涉及两个容器 networks 需要 3网段(1个容器分配3个不同网络), 不确定是不是docker网络初始化冲突，概率性，docker还是不靠谱，这种复杂场景..

### Steps to Reproduce

docker 版本：24.0.7

docker compose:，大概类似

```
    rust-d-server:
      image: xxxxxx
      container_name: rust-d-server
      restart: always
      deploy:
        resources:
          limits:
            cpus: "0.2"
            memory: 8M
      ports:
        - "9888:9000"
      networks:
        a_network:
          ipv4_address: 192.163.63.2
        b_network:
          ipv4_address: 192.166.99.99
        c_network:
          ipv4_address: 172.100.99.99
      depends_on:
        - rust-c-server
```
不定时卡住的情况:
1.*_network 创建卡住
2.deploy limits 重启部署的时候突然爆满 导致改容器无法部署，变成已创建状态 一直卡着

所以，现在不知道是docker的bug还是1panel这边对接docker的问题

### Related log output

```shell

```

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Contact Information

_No response_

### 1Panel Version

1.10.29 lts

### Problem Description

![Image](https://github.com/user-attachments/assets/979dd030-ffd5-4c57-a560-dd0799ad1b04) This is all 7:47 and is still in progress..
There are 2 containers stuck on the underlying docker compose, which causes the task status here to be stuck...

Is it equivalent to saying that a task process is suspended infinitely?

Because it requires 3 network segments to involve two containers (one container allocates 3 different networks), it is not certain whether the docker network initialization conflict, probability, docker is still unreliable, such a complex scenario...

### Steps to Reproduce

docker version: 24.0.7

docker compose:, probably similar

```
    rust-d-server:
      image: xxxxxx
      container_name: rust-d-server
      restart: always
      deploy:
        resources:
          limits:
            cpus: "0.2"
            memory: 8M
      Ports:
        - "9888:9000"
      networks:
        a_network:
          ipv4_address: 192.163.63.2
        b_network:
          ipv4_address: 192.166.99.99
        c_network:
          ipv4_address: 172.100.99.99
      depends_on:
        - rust-c-server
```
Status stuck at irregular intervals:
1.*_network creation stuck
2.deploy limits suddenly fills when restarting the deployment, causing the modifying container to be unable to deploy, and it becomes a created state and is stuck.

So, now I don’t know if it is a bug in docker or a problem with 1panel docking docker on the docker side

### The expected correct result

_No response_

### Related log output

```shell

```

### Additional Information

_No response_
