### ISSUE TITLE
[Bug] Django Static & Media files are not accessible even after adding config to Reverse Proxy

### ISSUE THREAD

**Issue by arnabJ** [1Panel-dev/1Panel#8808]
### 1Panel Version

v1.10.29-lts

### Problem Description

I have created a run.sh file and provided the same as command to start he project:
```bash
# run.sh

pip install -U virtualenv
virtualenv venv
. venv/bin/activate
pip install -r requirements.txt
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput
gunicorn --workers 3 --bind 0.0.0.0:4001 mydjangoproject.wsgi:application
```

The Python Runtime is started and the website is accessible. DEBUG_MODE is set to False. But I have also tried with set to True.

Then I added these lines to the Openresty config:
```conf
location /static/ {
    root /www/PythonProjects/mydjangoproject/static/;
}

location /media/ {
    root /www/PythonProjects/mydjangoproject/media/;
}
```
I also tried this variation:
```conf
location ^~ /static {
    root /www/PythonProjects/mydjangoproject;
}

location ^~ /media {
    root /www/PythonProjects/mydjangoproject;
}
```

But either way the static and media files are not accessible.

### Steps to Reproduce

Deploy a django project and try to access static or media files. You will get 404 Not Found error.

### The expected correct result

The mydomain/static/file or mydomain/media/file should be accessible.

### Related log output

```shell

```

**Comment by arnabJ** [comment]
The error I am seeing in error-log:


```log
2025/05/24 13:40:04 [error] 704#704: *19944 open() "/www/PythonProjects/mydjangoproject/static/admin/simpleui-x/img/bg.svg" failed (2: No such file or directory), client: 152.56.132.196, server: mydomain.com, request: "GET /static/admin/simpleui-x/img/bg.svg HTTP/2.0", host: "mydomain.com", referrer: "https://mydomain.com/"
```

The file exists and I have confirmed the same multiple times.

**Comment by arnabJ** [comment]
## Making static and media files accessible via openresty

Anybody looking to deploy a Django project with 1panel and having issue with static or media files follow these steps:

Make sure that the static and media files in the host machine are created were the openresty container can access them that is in 
`/opt/1panel/apps/openresty/openresty/www/sites/<WEBSITE>/index`

The reason behind this is that since even the reverse proxy is inside a container, it can only access those host directories which are mapped to it via volume.

---
## Django Project (Python Runtime) docker-compose.yml

To successfully run collectstatic inside your python container and to make sure that the files are uploaded to proper directory in host follow this step:

In the docker-compose.yml for your Django application add these to the volumes section:
```yml
- /opt/1panel/apps/openresty/openresty/www/sites/<WEBSITE>/index/static:/app/static
- /opt/1panel/apps/openresty/openresty/www/sites/<WEBSITE>/index/media:/app/media
```

Your final docker-compose.yml shouldl look similar to this:
```yml
networks:
    1panel-network:
        external: true
services:
    python:
        command: bash /run.sh
        container_name: ${CONTAINER_NAME}
        image: python:${PYTHON_VERSION}
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:${APP_PORT}
        restart: on-failure:5
        volumes:
            - ${CODE_DIR}:/app
            - ./run.sh:/run.sh
            - ./.env:/.env
            - /opt/1panel/apps/openresty/openresty/www/sites/<WEBSITE>/index/static:/app/static
            - /opt/1panel/apps/openresty/openresty/www/sites/<WEBSITE>/index/media:/app/media
        working_dir: /app
```
