### ISSUE TITLE
[Feature] XXL-JOB

### ISSUE THREAD

**Issue by iygwei** [1Panel-dev/1Panel#8849]
### 1Panel Version

v2.0.0-beta.3

### Please describe your needs or suggestions for improvements

可以把这个加入官方的商店这个还是很常用,不管是php还是Java

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下该项目的 docker run 命令或 docker-compose.yml 文件，方便我们后续适配上架。

**Comment by iygwei** [comment]
docker pull xuxueli/xxl-job-admin

**Comment by wanghe-fit2cloud** [comment]
> docker pull xuxueli/xxl-job-admin

由于我们之前未接触过该应用，建议提供完整运行命令。

**Comment by iygwei** [comment]
```yaml
services:
  mysql:
    image: mysql:5.7
    container_name: xxl-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xxl_job
      MYSQL_USER: xxl
      MYSQL_PASSWORD: xxl123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      PARAMS: >
        --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        --spring.datasource.username=xxl
        --spring.datasource.password=xxl123
    restart: always
```
