### ISSUE TITLE
[Bug] [MACVLAN] Reset ip after Upgrade from Image

### ISSUE THREAD

**Issue by reddexx** [1Panel-dev/1Panel#8950]
### 1Panel Version

1.10.29-lts

### Problem Description

Reset ip after Upgrade from Container

Before

![Image](https://github.com/user-attachments/assets/fae83666-10fa-4146-b51e-5f7e5fa6e071)

After Upgrade from Container

![Image](https://github.com/user-attachments/assets/6148ddcf-1298-4f72-b84a-e36c65a6907c)

### Steps to Reproduce

More > Upgrade > Confirm

![Image](https://github.com/user-attachments/assets/7c38911b-16d7-4f0e-9805-d6f7fc1c8af0)

Always pull image is no matter

### The expected correct result

IP not Change by Upgrade from Container

### Related log output

```shell
no Errors
```

**Comment by reddexx** [comment]
A Workaround is:

**more -> edit -> Always pull image**

this works!

**Comment by wanghe-fit2cloud** [comment]
Thanks for the feedback! If you’re using macvlan mode, the container’s IP normally shouldn’t change after an upgrade.

To help us troubleshoot, could you share the docker-compose.yml or the command you used to create the container?

**Comment by reddexx** [comment]
i use the Compose funcion from 1panel
here the Compose:

```yml
version: '3.8'
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy  # The Docker image to use.
    container_name: wg-easy         # Name of the container.
    environment:                    # Environment variables to configure the instance.
      - LANG=de                     # Language settings.
      - WG_HOST=secxxxxxx.xx   # Public IP or domain name where WG-Easy is accessible.
      - PORT=15555                  # Port for the web interface.
      - WG_PORT=51821               # WireGuard port for VPN traffic.
      - UI_CHART_TYPE=1
      - UI_TRAFFIC_STATS=true
      - WG_DEFAULT_DNS=192.168.179.1
    volumes:
      - ./wg-easy/:/etc/wireguard   # Volume mapping for WireGuard configuration files.
    ports:
      - "15555:15555/udp"           # UDP port used by WireGuard.
      - "51821:51821/tcp"           # TCP port for accessing the web interface.
    cap_add:                        # Capabilities required for managing networking features.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:                        # Kernel parameters that need to be set for WireGuard.
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped         # Ensures the container restarts automatically unless manually stopped.
```

i edit after create the Container and Edit the network adapter and the IP, is this wrong?

in Portainer works this 😅

**Comment by wanghe-fit2cloud** [comment]
Thanks for the details!
From the docker-compose.yml you shared, it looks like you’re using the default bridge network.
If you want the container to have a fixed IP, we recommend using the macvlan network driver directly in the compose file.

**Comment by reddexx** [comment]
ok i fix this Compose, thanks :)

**Comment by reddexx** [comment]
@wanghe-fit2cloud 

hi this Compose Script with MACVLAN Network not Working the IP-Adress Change after Upgrade from Container

**Comment by reddexx** [comment]
```yaml
version: "3.7"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /dein/eigener/pfad/work:/opt/adguardhome/work
      - /dein/eigener/pfad/conf:/opt/adguardhome/conf
    # Notiz: Die Ports werden direkt über die zugewiesene MACVLAN-IP-Adresse angesprochen.
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    networks:
      MACVLAN:
        ipv4_address: 192.168.178.226

networks:
  MACVLAN:
    external: true
```
