### ISSUE TITLE
[Feature] Add NapCat to the App Store

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#9190]
### 1Panel Version

Pro 2.0.1

### Please describe your needs or suggestions for improvements

RT,NapCat是一个基于TypeScript构建的Bot框架,通过相应的启动器或者框架,主动调用QQ Node模块提供给客户端的接口,实现Bot的功能。
文档链接: [NapCatQQ | 现代化的基于 NTQQ 的 Bot 协议端实现](https://napneko.github.io)
Github仓库: [NapNeko/NapCatQQ](https://github.com/NapNeko/NapCatQQ)
(社区作品)1Panel应用版本: [Fahaxikiii/napcat-1panel](https://github.com/Fahaxikiii/napcat-1panel)

### Please describe the solution you suggest

官方Docker Compose yml:
```yml
version: "3"
services:
    napcat:
        environment:
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}
        ports:
            - 3000:3000
            - 3001:3001
            - 6099:6099
        container_name: napcat
        network_mode: bridge
        restart: always
        image: mlikiowa/napcat-docker:latest
```

(自己写的)适配1Panel版本的yml
```yml
version: "3"  
services:  
  napcat:  
    image: mlikiowa/napcat-docker:v4.7.78
    container_name: ${CONTAINER_NAME}
    restart: always  
    networks:  
      - 1panel-network
    ports:  
      - ${PANEL_APP_PORT_HTTP}:6099
    environment:
      - TZ=Asia/Shanghai
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    labels:  
      createdBy: "Apps"  
  
networks:  
  1panel-network:  
    external: true
```
> 镜像版本与[GitHub Release](https://github.com/NapNeko/NapCatQQ/releases)一致,当然也可以是`latest`。
> 端口似乎只能让用户自己根据需要去放开,你总不能全部暴露吧。

(自己写的)应用声明文件
```yml
additionalProperties:
    key: napcat
    name: NapCat
    tags:  
        - Tool
        description:
          zh: 现代化的基于 NTQQ 的 Bot 协议端实现
    type: tool
    crossVersionUpdate: true
    limit: 0
    website: https://napneko.github.io
    github: https://github.com/NapNeko/NapCatQQ
    document: https://napneko.github.io/guide/start-install
```

(自己写的)应用参数配置文件
```yml
additionalProperties:
  formFields:
  - default: 6099 
    edit: true  
    envKey: PANEL_APP_PORT_HTTP
    required: true  
    type: number
    rule: paramPort
    label:
      zh: WebUI端口
```

### Additional Information

我对Docker Compose研究不深,自己写的只是照着改,因此可能有些不太正确或者会缺什么。\
应用参数配置文件*可能*还可以配置更多,可以参考上面提到[1Panel应用版本仓库里的napcat分支](https://github.com/Fahaxikiii/napcat-1panel/tree/napcat)。

顺便借此issue提一下,你们GitHub Wiki上的应用tags字段缺了很多。
