### ISSUE TITLE
[Feature] Please request the App Store to add the following three applications: allinssl, ech0, and whoDB

### ISSUE THREAD

**Issue by willow-god** [1Panel-dev/1Panel#9211]
### 1Panel Version

2.0.2

### Please describe your needs or suggestions for improvements

请求将以下三个应用适配至 1Panel App Store，均为轻量化、易部署的 Docker 应用，适合社区用户快速体验与实际部署。

---

### 1️⃣ [[allinssl](https://github.com/allinssl/allinssl)](https://github.com/allinssl/allinssl) - 自动化证书申请与续签工具

**简介：**
`allinssl` 是一个基于 Web 界面的 SSL 证书自动化申请与续签工具，支持国内外主流 DNS 服务商，适用于希望可视化和自动化管理 SSL 的用户。

**原生 Docker 命令：**

```bash
docker run -itd \
  --name allinssl \
  -p 7979:8888 \
  -v /www/allinssl/data:/www/allinssl/data \
  -e ALLINSSL_USER=allinssl \
  -e ALLINSSL_PWD=allinssldocker \
  -e ALLINSSL_URL=allinssl \
  -e TZ=Asia/Shanghai \
  allinssl/allinssl:latest
```

**推荐 Docker Compose 转换配置：**

```yaml
version: "3.8"
services:
  allinssl:
    image: allinssl/allinssl:latest
    container_name: allinssl
    ports:
      - "7979:8888"
    environment:
      - ALLINSSL_USER=allinssl
      - ALLINSSL_PWD=allinssldocker
      - ALLINSSL_URL=allinssl
      - TZ=Asia/Shanghai
    volumes:
      - /www/allinssl/data:/www/allinssl/data
```

---

### 2️⃣ [[Ech0](https://github.com/lin-snow/Ech0)](https://github.com/lin-snow/Ech0) - 极简轻量说说应用

**简介：**
`Ech0` 是一个极简的轻博客/说说应用，后端基于 SQLite，开箱即用，界面美观，配置零依赖，适合搭建私人轻量内容记录站。

**官方提供的 Compose 文件：[[传送门](https://github.com/lin-snow/Ech0/blob/main/docker-compose.yml)](https://github.com/lin-snow/Ech0/blob/main/docker-compose.yml)**
无需额外数据库服务，启动即用。

```yaml
version: '3'
services:
  ech0:
    image: ghcr.io/lin-snow/ech0:latest
    ports:
      - 8081:80
    volumes:
      - ./data:/app/data
    restart: unless-stopped
```

---

### 3️⃣ [[whoDB](https://github.com/clidey/whodb)](https://github.com/clidey/whodb) - 数据库可视化 + AI 智能查询平台

**简介：**
`whoDB` 是一个现代化数据库可视化工具，支持本地数据库浏览与通过 API 接入 AI（如 OpenAI、Anthropic、Ollama）进行智能 SQL 生成与问答。

**功能亮点：**

* 支持多数据库连接（PostgreSQL、SQLite、MySQL 等）
* 可本地运行 Ollama LLM 或远程接入 OpenAI/Anthropic
* 提供 Web UI 实现 AI 辅助数据库交互

**Compose 配置示例：**

```yaml
version: "3.8"
services:
  whodb:
    image: clidey/whodb
    ports:
      - "8080:8080"
    environment:
      - WHODB_OPENAI_API_KEY=your_openai_key_here
#     - WHODB_OLLAMA_HOST=localhost
#     - WHODB_ANTHROPIC_API_KEY=your_anthropic_key_here
    # volumes: # 如需使用本地 SQLite 可挂载如下
    #   - ./sample.db:/db/sample.db
```

以上三个应用均较为实用，第一个为SSL全自动续签工具，目前应用中已经有Certimate，但是并不影响AllinSSL也是较为优秀的项目，第二个为说说，目前应用商店中除了Memos可以作为轻量的说说发布页面，似乎没有更加合适的说说项目。第三个为数据库管理，相比于已有的phpmyadmin，whoDB提供了更加完善的数据库支持，并且界面也更加美观，并且可以根据需要接入大模型，大大提升了易用性。

### Please describe the solution you suggest

请求官方适配以上应用，谢谢开发者！

### Additional Information

无
