### ISSUE TITLE
[Feature] Hope the App Store can add support for the NATS application

### ISSUE THREAD

**Issue by zhouw1015** [1Panel-dev/1Panel#9309]
### 1Panel Version

2.0.2

### Please describe your needs or suggestions for improvements

希望应用商店增加NATS应用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！你是否有推荐的开源应用？
要支持 Docker 容器化部署，并且最好是在 GitHub 等平台开源的项目。

**Comment by zhouw1015** [comment]
> 感谢反馈！你是否有推荐的开源应用？ 要支持 Docker 容器化部署，并且最好是在 GitHub 等平台开源的项目。

https://github.com/nats-io/nats-server.git

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈！你是否有推荐的开源应用？ 要支持 Docker 容器化部署，并且最好是在 GitHub 等平台开源的项目。
> 
> https://github.com/nats-io/nats-server.git

麻烦提供你平时使用该应用的容器化部署方案，例如 docker run 命令或 docker-compose.yml 文件。

**Comment by zhouw1015** [comment]
> > > 感谢反馈！你是否有推荐的开源应用？ 要支持 Docker 容器化部署，并且最好是在 GitHub 等平台开源的项目。
> > 
> > 
> > https://github.com/nats-io/nats-server.git
> 
> 麻烦提供你平时使用该应用的容器化部署方案，例如 docker run 命令或 docker-compose.yml 文件。

不使用集群：
docker run --name nats --network nats --rm -p 4222:4222 -p 8222:8222 nats --http_port 8222

使用 Docker Compose 创建 NATS 集群：
```yaml
version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats
```


docker-compose -f nats-cluster.yaml up
